### ISSUE TITLE
HELP! Does JKSV keep save data somewhere if you delete game save data?

### ISSUE THREAD

**Issue by pointypancake1** [J-D-K/JKSV#101]
I was trying to get rid of some older save folders in jksv for breath of the wild but I accidentally deleted the data that the game has I have an older save file but its super far back like at the great plateau and the save data i had already had 3 divine beasts does jksv have a backup anywhere?

**Comment by fennectech** [comment]
Yes.  It is still on your SD card.    You need to open the game to get it to appear again.

**Comment by J-D-K** [comment]
No, if I'm understanding you right. A trash bin is planned for the future but for now, if the folder/zip is gone, it's gone.

**Comment by fennectech** [comment]
You can look into a tool called Recuvia
