### ISSUE TITLE
Error trying to restore Pokémon Snap backup

### ISSUE THREAD

**Issue by Alxzu** [J-D-K/JKSV#102]
After successfully creating the backup on one of my SDs I tried to restore the backup on a new emuNAND with this error

![20210705_181537](https://user-images.githubusercontent.com/8084303/125109304-8e8b5680-e0b9-11eb-953c-6e22c1aa7884.jpg)

Atmosphere 0.19.4 | 0.19.5
Firmware: 12.0.3

I saw [this post](https://gbatemp.net/threads/jksv-not-compatible-with-new-pokemon-snap.587907) about Pokémon Snap injecting the console's ID into the backup, but in this case is the very same console so not sure that's the problem

**Comment by J-D-K** [comment]
It's not because of anything related to ID's. The main save file is large and the system runs out of journal space. You need my latest [prerelease](https://github.com/J-D-K/JKSV/releases/tag/05.17.2021) to restore it.

**Comment by Alxzu** [comment]
Downloaded the prerelease version, copied into `switch/JKSV/JKSV.nro` getting a crash like this one
![Screen Shot 2021-07-10 at 12 24 11](https://user-images.githubusercontent.com/8084303/125168015-bf32c500-e179-11eb-98cf-d2665e6c8c2b.png)

I tried with applet mode too, getting an error and closing (no crashing tho)

**Comment by J-D-K** [comment]
That's odd. I don't remember changing anything related to data loading between those releases. I'll get back to you later.

**Comment by J-D-K** [comment]
[jksv_zip.zip](https://github.com/J-D-K/JKSV/files/6796202/jksv_zip.zip)
You can try one of these. They're the latest I've got. I don't recommend using the newest one for more than getting your save back if it starts. It's still early, buggy and just barely works at this point.

**Comment by Alxzu** [comment]
😞  I'm afraid I'm getting the same results. Thanks for the help, this could be an issue with my cfw

**Comment by J-D-K** [comment]
Did you get anywhere?

**Comment by Alxzu** [comment]
I didn't... fresh setup same results. I'll wait for the stable realease. Thanks for being on the lookout

**Comment by J-D-K** [comment]
I'd rather get it figured out and get your stuff back for ya. It would help making a stable build. Try this build. If it still crashes, open your JKSV folder, ZIP the `log.txt` file and post it here. It'll pinpoint what title is preventing JKSV from booting.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/6834077/JKSV.zip)

**Comment by Alxzu** [comment]
- Deleted the folder JKSV from root path
- Deleted the JKSV folder from /switch
- Crated a folder JKSV with the JKSV.nro file inside /switch folder
- Tried to run it hbmenu with full memory

`The software was closed because an error occurred`

The weird thing is the logs are empty

![Uploading Screen Shot 2021-07-17 at 00.50.49.png…]()

**Comment by J-D-K** [comment]
The load screen doesn't even pop up? That means it's crashing before it even really starts. Before the data is loaded and sorted, all that really happens is that services are started and a few colors are set.

**Comment by Alxzu** [comment]
With the stable release, I used to be able to access the main UI... I'm trying with the stable right now but getting the same results as the new candidates versions 🤔  maybe I screw it up

**Comment by J-D-K** [comment]
You went back to 06.07.2020 and same problem you mean? I'm pretty picky. I don't push code or give builds unless I know they're pretty stable for myself. Are you using Fat32?

**Comment by Alxzu** [comment]
Yes, the same issue as this one https://github.com/J-D-K/JKSV/issues/102#issuecomment-877655346. I also tried with the NSP getting the `The software was closed because an error occurred`.... In my first post (when I created this issue) you can see I was able to access the main UI... Not sure what I could have done to break it

**Comment by Alxzu** [comment]
Fat32 yes

**Comment by J-D-K** [comment]
Are you using any sysmodules? Sometimes they eat too much memory and cause problems. That's the last of my ideas.

**Comment by Alxzu** [comment]
It was memory issues indeed! Disabling Tesla module & BT controller module did the trick!!! I'm using the emergency release that you provide on the releases page. Thanks for all the help! I'd love to buy you a cup of coffee or something 😄
