### ISSUE TITLE
Feedback on NewUI 

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#103]
1.  I would like to be able to have moving up and down the left most column automatically select the item. Instead of having to press A on the column.   
2. I would like to be able to use left and right on the dpad to enter the main panel where the items are

**Comment by J-D-K** [comment]
Menu class still needs a lot of work since it's still 2016 3DS code. I'll keep it in mind and see if I can pull it off.

**Comment by fennectech** [comment]
Additionally. If you enter the extras pane you are stuck there forever. You must close jksv to escape it

**Comment by J-D-K** [comment]
Yeah, I knew about that. The function to make it jump and change to it is there but I didn't get to implementing the extras yet since that's one of the least important things to get done. The menu has been implemented and it has been fixed in the latest commits. The menu doesn't do much though.

**Comment by fennectech** [comment]
Any chance we will be able to get the PKSM bridge?

**Comment by fennectech** [comment]
If the user clicks "NEW" and does not input anything for the name  it would be nice if iit used the normal auto date time one

**Comment by fennectech** [comment]
`A trash bin folder has been added. If trash is enabled, deleted backups will be sent to the _TRASH_ folder instead of being permanently deleted. This is likely to change in the future to separate different titles. `

I vote subfolders in the _TRASH_ folder

**Comment by ELY3M** [comment]
I just got new JKSV and I was not happy.  I cant press UP to get to the last thing in the list.      
in old JKSV (8-1-21 version) I was able to do that and get to the folder named own easy and quick.

**Comment by J-D-K** [comment]
One of the early revisions of the scrolling menu code didn't play to nice with jumping to the top or bottom. It's been fixed if you can build the source yourself. If not, give me some time and I'll build it for you.

**Comment by ELY3M** [comment]
Thank you.  I will build and test.

**Comment by J-D-K** [comment]
No problem. I was updating the readme, so if you need the updated lib list:
`pacman -S switch-curl switch-freetype switch-libjpeg-turbo switch-libjson-c switch-libpng switch-libwebp switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-zlib`
I believe that should do it.

**Comment by fennectech** [comment]
Most use dkp-pacman not their native system package manager.

**Comment by ELY3M** [comment]
I use pacman

**Comment by fennectech** [comment]
I also use pacman   but it would be wise to recommend dkp-pacman as thats
what is recommended to be used by the switchbrew team and what the majority
will use.

**Comment by ELY3M** [comment]
update:   I built latest JKSV code and the scrolling is way better :)    I can easily press up to go to the bottom of the saves list now.      

Thank you

**Comment by jritza** [comment]
Please add a text navigation option for the new UI. 

I have an immense amount of games I have to scroll through and it's frustrating to look through the text on tiny pictures to find the correct game. It is even worse with demos, which use the same picture as the full game so I don't even know which I am selecting. It doesn't make any sense to force users to use this ridiculous inefficient interface. 

The favorites option is a lazy band-aid on this glaring issue. If no efforts are made to fix the interface, at least make version 08.01.2021, the last version of JKSV with text navigation, compatible with recent Switch version font changes.
