### ISSUE TITLE
[feature request]give up and dont waste youre time

### ISSUE THREAD

**Issue by flagbrewbrewfan04** [J-D-K/JKSV#105]
THIS IS COMPLETELY A JOKE!!!! you are the JOKE since on 3ds. stop wasting youre time.no person on planet earth use jksv and stop stealing checkpoint code THIEF!!! jksv corrupt my whole switch and brick!!!! jksv is inferior checkpoint clone since on 3ds and way worse with stolen codes. 
this my warning to all stay away.and use real savemanager

**Comment by fennectech** [comment]
Ive been using JKSV for years.   Do you by any chance have an exfat SD card?  If so. Thats what corrupted your switch.   Not jksv.  The fact that deepsea ships jksv by default proves you wrong.  As does the many people making issues here.    Stop tantraming and dont fill the issue tracker with pointless garbage.

**Comment by Slluxx** [comment]
@flagbrewbrewfan04 wtf is wrong with you

**Comment by Conan179** [comment]
The troll is just mad that jksv is still being developed. Checkpoint are not around 2 years, always the fanboy trolls.

**Comment by J-D-K** [comment]
Kek. Sorry I bricked your switch. Must've been all that checkpoint code I stole. Also is this you too? https://github.com/J-D-K/JKSV/issues/38#issue-629159784

@fennectech
Unless I make a note in the readme, it's safe to assume I wrote it. Anybody that has actually talked to me will tell you I'm really stubborn when it comes to using code from other projects. I don't even understand what there is to steal, especially now, or why I would even need to? The original JKSM had nothing to steal from in the first place and switch was just a port originally. The only way that makes sense at all is to ignore I wrote it in 2015 and released early 2016.

Anyways, just ignore him. He made a burner account today and I'm sure he won't have the balls to come back. He's just butthurt there's something JKSV can do that he wants but his blind hatred won't allow him to use it.

**Comment by fennectech** [comment]
The ability to enlarge save containers is tits.  (And they upload to NSO too!

**Comment by fennectech** [comment]
> Unless I make a note in the readme, it's safe to assume I wrote it. Anybody that has actually talked to me will tell you I'm really stubborn when it comes to using code from other projects.

Even if you did.  There would be absolutely nothing wrong with 'stealing' open source code from one GPLv3 project to another GPLv3 project.   ITs litteraly the point of GPLv3

**Comment by fennectech** [comment]
Is there any change of adding the PKSM bridge?   It acts as a server to serve a save file to pksm over the network for save editing on PKSM switch app.  Its really simple and only applies to Pokemon games.

**Comment by J-D-K** [comment]
I don't know yet. My plans are to get switch fully up and running, take a break and then I promised some people I'd backport switch ui to 3ds. My plate is kinda full and my time as it is is limited.

**Comment by J-D-K** [comment]
A lot of what I'm doing right now was planned and needed. Save extending is needed for New Snap but also I was contacted months ago about it for Cache saves since I guess you can load custom Doom maps that way. Pokémon new snaps journal space fix also fixes a lot of errors related to committing data. Save creation was asked a long, long time ago. Before the call was added to libnx. I added the call in myself close to a year ago, but got sidetracked. People contact me a lot through Gbatemp messages. I have a pretty long list to get through. I'm also considering some kind of cloud backup at this point. I've accidentally deleted my own Skyward Sword save twice now testing things. I had backups, but not quite where I had progressed to.
