### ISSUE TITLE
JKSV being open prevents ftpd from getting listing. 

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#108]
would it be possible to close your handle to /jksv/ when your not directly using it?  this will let filezilla get a directory listing

**Comment by J-D-K** [comment]
I think this should do it. The only thing I have open 100% of the time is the log file. Also, for your other comment about auto naming, just hold one of the shoulder buttons to get the name you want. Blank strings are how I check/let people cancel input.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/6910371/JKSV.zip)

**Comment by fennectech** [comment]
That closes this!

**Comment by fennectech** [comment]
As for the other one.  Is there any way to preload default name into the keyboard?

**Comment by fennectech** [comment]
As for deternining weather the user canceled input. The keyboard returns "decidedenter" or "decidedcancel" as per this page on switch brew  https://switchbrew.org/wiki/Software_Keyboard.    If the kbd returns "Decidedenter" use auto name. If the kbd returns "decideccancel" consider the user having bailed out.

**Comment by fennectech** [comment]
ChangedString and ChangedStringV2 could also be of use for this

**Comment by J-D-K** [comment]
I load up the keyboard dictionary with suggestions that include the date formats, an auto generated abbreviation (not perfect), your username, and the title itself if it's safe. You have to type 2 or the first letter of the game title for them to show up. I don't think many people know that. I don't think anyone else took the time to figure out the dictionary word format.

**Comment by fennectech** [comment]
would be nice if i could just hit start and it would auto set the date   But that is a cool thing

**Comment by fennectech** [comment]
It should be possible as games are able to preload text into the swkbd

**Comment by J-D-K** [comment]
OK. I'll switch it over to using the return status instead. I wrote the keyboard stuff a long time ago while yellows was still working it all out IIRC.

**Comment by fennectech** [comment]
SICK.   Thanks.   Its amaizing to see the software improving so quickly!
