### ISSUE TITLE
Version 01.06.2020 - No user selectable in applet mode

### ISSUE THREAD

**Issue by muxi1** [J-D-K/JKSV#11]
If JKSV 01.06.2020 is executed via the HB menu in applet mode, no user can be selected.
![2020010709360200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/39792666/71881267-4b51cf80-3132-11ea-95f3-6300a621777a.jpg)

If it is executed via the HB menu in high memory mode, however, it is.
![2020010709363500-D63E988A3C2BE869A390AA6D223D4D3E](https://user-images.githubusercontent.com/39792666/71881458-9ff54a80-3132-11ea-8360-8c290db310f0.jpg)

**Comment by J-D-K** [comment]
Thanks. I'll check it out.

**Comment by J-D-K** [comment]
I just uploaded an updated version. Let me know if it works for you too.

**Comment by muxi1** [comment]
The error is now fixed! Thanks a lot!
