### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yyoossk** [J-D-K/JKSV#110]
$ make
data.cpp
aarch64-none-elf-g++ -MMD -MP -MF /home/hiroki2/jksv/build/data.d `sdl2-config --cflags`        -g -Wall -O2 -ffunction-sections -ffast-math -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/home/hiroki2/jksv/inc -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/home/hiroki2/jksv/build -D__SWITCH__ `freetype-config --cflags` `curl-config --cflags` -fno-rtti -fno-exceptions -std=gnu++17 -c /home/hiroki2/jksv/src/data.cpp -o data.o
In file included from C:/Users/hiroki2/jksv/inc/util.h:5,
                 from C:/Users/hiroki2/jksv/src/data.cpp:12:
C:/Users/hiroki2/jksv/inc/ui.h:40:12: error: 'PadState' does not name a type
   40 |     extern PadState pad;
      |            ^~~~~~~~
C:/Users/hiroki2/jksv/inc/ui.h: In function 'void ui::updatePad()':
C:/Users/hiroki2/jksv/inc/ui.h:41:49: error: 'pad' was not declared in this scope
   41 |     static inline void updatePad() { padUpdate(&pad); }
      |                                                 ^~~
C:/Users/hiroki2/jksv/inc/ui.h:41:38: error: 'padUpdate' was not declared in this scope; did you mean 'noUpdate'?
   41 |     static inline void updatePad() { padUpdate(&pad); }
      |                                      ^~~~~~~~~
      |                                      noUpdate
C:/Users/hiroki2/jksv/inc/ui.h: In function 'uint64_t ui::padKeysDown()':
C:/Users/hiroki2/jksv/inc/ui.h:42:63: error: 'pad' was not declared in this scope
   42 |     inline uint64_t padKeysDown() { return padGetButtonsDown(&pad); }
      |                                                               ^~~
C:/Users/hiroki2/jksv/inc/ui.h:42:44: error: 'padGetButtonsDown' was not declared in this scope; did you mean 'hidMouseButtonsDown'?
   42 |     inline uint64_t padKeysDown() { return padGetButtonsDown(&pad); }
      |                                            ^~~~~~~~~~~~~~~~~
      |                                            hidMouseButtonsDown
C:/Users/hiroki2/jksv/inc/ui.h: In function 'uint64_t ui::padKeysHeld()':
C:/Users/hiroki2/jksv/inc/ui.h:43:59: error: 'pad' was not declared in this scope
   43 |     inline uint64_t padKeysHeld() { return padGetButtons(&pad); }
      |                                                           ^~~
C:/Users/hiroki2/jksv/inc/ui.h:43:44: error: 'padGetButtons' was not declared in this scope
   43 |     inline uint64_t padKeysHeld() { return padGetButtons(&pad); }
      |                                            ^~~~~~~~~~~~~
C:/Users/hiroki2/jksv/inc/ui.h: In function 'uint64_t ui::padKeysUp()':
C:/Users/hiroki2/jksv/inc/ui.h:44:59: error: 'pad' was not declared in this scope
   44 |     inline uint64_t padKeysUp() { return padGetButtonsUp(&pad); }
      |                                                           ^~~
C:/Users/hiroki2/jksv/inc/ui.h:44:42: error: 'padGetButtonsUp' was not declared in this scope
   44 |     inline uint64_t padKeysUp() { return padGetButtonsUp(&pad); }
      |                                          ^~~~~~~~~~~~~~~
C:/Users/hiroki2/jksv/src/data.cpp: In member function 'void data::user::loadPlayTimes()':
C:/Users/hiroki2/jksv/src/data.cpp:468:94: error: cannot convert 'bool' to 'PdmPlayStatistics*'
  468 |                 pdmqryQueryPlayStatisticsByApplicationIdAndUserAccountId(_d.getID(), userID, false, &stats);
      |                                                                                              ^~~~~
      |                                                                                              |
      |                                                                                              bool
In file included from C:/devkitPro/libnx/include/switch/services/applet.h:12,
                 from C:/devkitPro/libnx/include/switch.h:54,
                 from C:/Users/hiroki2/jksv/src/data.cpp:8:
c:\devkitpro\libnx\include\switch\services\pdm.h:194:120: note:   initializing argument 3 of 'Result pdmqryQueryPlayStatisticsByApplicationIdAndUserAccountId(u64, AccountUid, PdmPlayStatistics*)'
  194 | Result pdmqryQueryPlayStatisticsByApplicationIdAndUserAccountId(u64 application_id, AccountUid uid, PdmPlayStatistics *stats);
      |                                                                                                     ~~~~~~~~~~~~~~~~~~~^~~~~
C:/Users/hiroki2/jksv/src/data.cpp:475:70: error: cannot convert 'bool' to 'PdmPlayStatistics*'
  475 |                 pdmqryQueryPlayStatisticsByApplicationId(_d.getID(), false, &stats);
      |                                                                      ^~~~~
      |                                                                      |
      |                                                                      bool
In file included from C:/devkitPro/libnx/include/switch/services/applet.h:12,
                 from C:/devkitPro/libnx/include/switch.h:54,
                 from C:/Users/hiroki2/jksv/src/data.cpp:8:
c:\devkitpro\libnx\include\switch\services\pdm.h:186:88: note:   initializing argument 2 of 'Result pdmqryQueryPlayStatisticsByApplicationId(u64, PdmPlayStatistics*)'
  186 | Result pdmqryQueryPlayStatisticsByApplicationId(u64 application_id, PdmPlayStatistics *stats);
      |                                                                     ~~~~~~~~~~~~~~~~~~~^~~~~
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: data.o] Error 1
make: *** [Makefile:152: build] Error 2

**Comment by J-D-K** [comment]
Is your libnx up to date? What OS are you building on?

**Comment by yyoossk** [comment]
yes
windows10

**Comment by yyoossk** [comment]
sorry success!
