### ISSUE TITLE
improvement for file structure and config files

### ISSUE THREAD

**Issue by pixeltester** [J-D-K/JKSV#117]
Hello JK. I've been using JKSV a lot over the years and one thing I thought could be improved is how JKSV organizes its files.

Here is my suggestion if you'd consider it:

Store all the config and txt files that are generated at sd:/config/JKSV/ including making this the location for jksv_dir.txt and titledefs.txt, this config location is used by many homebrew for storing config files and it's useful so they don't accidentally get cleaned out with the switch folder and it also helps to keep that folder clean.

Then change jksv_dir.txt into jksv_save_dir.txt and make this file purely for choosing where your save files will be generated.

I hope the suggested changes make sense, thanks!

**Comment by fennectech** [comment]
i like this   Having a universal storage space (like /etc/ on linux) is convenient

**Comment by fennectech** [comment]
However. Json files for the trash contents and folder names (within jksv’s save folder) should remain in that folder as those are specific to the instillation.

**Comment by J-D-K** [comment]
I want to merge as many of the config files as possible soon and I'll move it there. I'm still deciding how I want to store everything. Binary is what I'd usually do for that but that wouldn't be easily edited by users outside of JKSV. I'm not a fan of json either. My datafile class could get the job done but that was ripped from an old game project script thing and isn't optimal.

**Comment by pixeltester** [comment]
That's great, a single config file that handles everything sounds even better! Wouldn't using .ini be simple and do the job well? It parses nicely in text editors too.

**Comment by J-D-K** [comment]
Well, the datafile class can already read stuff like that. You can take a look at the en-US.txt file in the romfs to see. I use that to load translations. I think if I add array support, it'll kill two birds. I can use it to tidy up translation files so menu strings don't need the index number and it'll allow me to put the fav,  blacklist and output folder changes into an array and get rid of those.

**Comment by J-D-K** [comment]
@pixeltester 
Does this seem OK? The only thing I'm not sure about is path definitions but they take two inputs, so weird C like thing it is.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/6948480/JKSV.zip)

**Comment by pixeltester** [comment]
> 
> 
> @pixeltester
> Does this seem OK? The only thing I'm not sure about is path definitions but they take two inputs, so weird C like thing it is.
> [JKSV.zip](https://github.com/J-D-K/JKSV/files/6948480/JKSV.zip)

That's great, already a big improvement!

I do think that titleDefs as its own file seperate from the config would be a good idea though, then it can be shared without overwriting configs (but still store it in the config folder alongside the main config). Also it can be quite a large list so it would keep the main config organized.

Maybe a bug - I tried a titleDefs entry in the usual format in the new config file and I got: titleid = "game name" but the folder name was a strange merge of the titleid and game name without spacing, also the trash folder had the same game name added to it somehow.

A couple of other things I wanted to ask you if that's ok, these are on the last version of jksv but I think they might get carried over?
1. could the headers error on zips extracted on windows be fixed do you think? I've seen other homebrews avoid it
2. if you use switch/JKSV/ as the jksvdir and try to backup the full jksv folder into a zip, it packs up the nro and all the other stuff, could that be avoided so it just packs the saves like other locations? I only ask as I think it's a good location for storing saves.

**Comment by J-D-K** [comment]
Ok. The old path definition format won't work with that config as it's kind of hard to know what's what in a config like that, but I'll separate them again and go back to the old one. I'll check out the zip thing and work on trimming the path down so that doesn't happen. I'll get the old path definitions back later but I'm taking a short break afterwards. I'm really starting to feel burned out and I don't want that to happen. I'll get back to ya.

**Comment by pixeltester** [comment]
> Ok. The old path definition format won't work with that config as it's kind of hard to know what's what in a config like that, but I'll separate them again and go back to the old one. I'll check out the zip thing and work on trimming the path down so that doesn't happen. I'll get the old path definitions back later but I'm taking a short break afterwards. I'm really starting to feel burned out and I don't want that to happen. I'll get back to ya.

Sure and sorry I didn't mean to apply any pressure, just wanted to give you as good suggestions as possible since you have this new version coming up. I'm perfectly happy with the original for the next week/month/year until whenever your new version is ready 👍

**Comment by fennectech** [comment]
We will need a migration tool   could you whip up a python script or soemthing  or do i need to do it manualy

**Comment by fennectech** [comment]
I did it manualy using find and replace to sort things out

**Comment by J-D-K** [comment]
I'll take care of it. I'm taking a break.

**Comment by fennectech** [comment]
Anyways.  Question. How do you do auto backup. I cant seem to.  I do “L + R + Y” isnt working any more

**Comment by J-D-K** [comment]
You hold one of the shoulder buttons while selecting New depending on what day format you prefer.

**Comment by fennectech** [comment]
I mean the bulk “Back up all the things” backup

**Comment by J-D-K** [comment]
Not implemented yet. I'm still deciding whether or not I'm going to change some things.

**Comment by fennectech** [comment]
So far.  NewUI is really turning out to be a banger!

**Comment by pixeltester** [comment]
The repo for a master title definition file is a really good idea!

I also think the new UI looks and animates really nicely, The only thing I would say is that the text in menus seems a little on the large side, but maybe I'm just too used to the original JKSV after using it for so long.

**Comment by J-D-K** [comment]
They are a tiny bit larger, but I only think it's a couple pixels. The menus are kind of a balancing act to be honest. It takes some careful tweaking to get them just right with the scrolling. Even then, they're not perfect.

They weren't as much of a nightmare as I thought though. Every other time I've touched them since 3DS, they usually break horribly but this time was surprisingly smooth.

**Comment by J-D-K** [comment]
Path definitions have been split from config, loading the old config and stuff has been taken care of. I'm not pushing the code because I'm trying to track down a bug. I updated the way translations work and there's a small issue that popped up.

**Comment by fennectech** [comment]
We could provide community provided path definitions that come with the app for games with enteirely fat32 uncomplient names (ie those that need a title ID

**Comment by J-D-K** [comment]
The issue I'm still trying to come up with a solution to is different regions. Quite a few games are world wide releases and use the same title ID. Each region would need a different master list since the US and UK would be a lot different than Japan or China for example. 

I'd also like to compile them on system specifically for the user as downloading and loading the master file is going to hurt boot time to an extent.

**Comment by J-D-K** [comment]
ZIP headers should be fixed now. I got mass backup back too in the user options slide out. I think I'm going to wait until I feel better to do much more because I'm having trouble focusing and remembering stuff. It's here if you want it. Old definitions should be moved to the config/JKSV folder now.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/7004106/JKSV.zip)

**Comment by pixeltester** [comment]
Thanks @J-D-K Really great work and everything you mentioned is working fine for me. I thought the definitions weren't moving automatically at first but realized that happens after they get used once by a game. In fact the only thing not implemented yet that I noticed and use myself is the backup folder option. I'm sure there are other bits that you are aware of but it's looking quite complete now!

**Comment by J-D-K** [comment]
They should be when the config is loaded. I'll check it out. It's possible the configs are conflicting from different build changes. It shouldn't happen anymore.

**Comment by J-D-K** [comment]
@pixeltester It's back now, with path trimming and it should ignore everything except folders (trash folder should be ignored too). Unfortunately I had something go wrong with DOOM's BCAT and it basically bricked my Switch and I had to factory reset (I fixed that too BTW... I think?). So, I don't have anything to really test with besides backups from recent stuff I've been playing. If you don't mind, let me know if anything is off now.
[JKSV - 08.19.2021.zip](https://github.com/J-D-K/JKSV/files/7018441/JKSV.-.08.19.2021.zip)

**Comment by pixeltester** [comment]
@J-D-K wow sorry to hear about the brick! Tested that one for you by adding my old JKSV files and removing the newUI version and new config files.

- backup folder seems to work perfectly, looks like it ignores everything except the games as you said
- the new config file generates from the old one on the first boot of newUI JKSV, jksv_dir.txt gets deleted but the old cfg.bin gets left behind (not really important though)
- slightly weird issue but for some reason titledefs doesn't seem to get moved and converted until the second time you start the new version of JKSV. So on the very first time you run newUI JKSV coming from an older version you won't have titledefs and won't see older saves made using them

**Comment by J-D-K** [comment]
Ok. Thanks. I'll see if I can get it all straightened out. I'm glad it happened now and to me instead of later and someone else. I didn't really lose much I actually wanted, just a pain really.

**Comment by pixeltester** [comment]
@J-D-K Something seems wrong with this in the release version, titledefs only worked once and now isn't being read even though it's converted and in the sd:/config/JKSV/ folder, and now the old title folders without names are being generated instead.

**Comment by J-D-K** [comment]
I think i know what's up. I'll fix it when I get home later.

**Comment by J-D-K** [comment]
I think I got it. The old function took care of both, but to get it working right, I had to separate the loading routines and being as tired as I usually am, I forgot to add the updated one. Should be good to go, but if not, let me know.
