### ISSUE TITLE
FR translation

### ISSUE THREAD

**Issue by shadow2560** [J-D-K/JKSV#122]
I've made a translation for french language, probably not perfect but I think that it's a good begining.
[fr.txt](https://github.com/J-D-K/JKSV/files/7095477/fr.txt)

**Comment by J-D-K** [comment]
Thank you. I have added it and the code to load it. Unfortunately, I am from North America, so it assumes when I pick French, I mean Canadian French. I can't actually check if it loads it correctly once I remove the case for Canadian French, but I assume it should.

**Comment by J-D-K** [comment]
Cool. I got it. I was working on something, so it might be a little while before the update release. Thanks.

**Comment by shadow2560** [comment]
Here is an update for fr translation based on commit e3d54be:
[fr.txt](https://github.com/J-D-K/JKSV/files/7653132/fr.txt)

**Comment by J-D-K** [comment]
Thanks. I'll try to get it added later today or tomorrow.
