### ISSUE TITLE
Corrupted Saves

### ISSUE THREAD

**Issue by NimrodMiki** [J-D-K/JKSV#123]
Skyrim makes big save files. If there is a lot of save files, only around the first 20 save slots gets restored, the other ones get corrupted with minimal data. This issue has been present from long time ago.

**Comment by J-D-K** [comment]
Does Skyrim increase its save size on the system? I don't think it's an issue with file size, because there are games that use 1GB+ and don't have issues. That sounds like what happens if the container runs out of space. I can try adding auto extend later if you want to see if that helps?

**Comment by TheCatHacker562** [comment]
try not to use exfat, use fat32
exfat will eventually corrupt your sd card

**Comment by J-D-K** [comment]
I don't think this is a fat32/exfat problem. I don't own Skyrim on Switch to find out either or I'd just fix it now.

**Comment by NimrodMiki** [comment]
I use fat32. I dont really now how to find out the root cause, but i
experience it on multiple devices when there are a lot of saves in skyrim.
On older versions the restore progress just stopped, the new ones finish
restoring, but after like 20 files, there is no data in the files.


JK ***@***.***> ezt írta (időpont: 2021. szept. 4., Szo 0:19):

**Comment by fennectech** [comment]
Ive got Skyrim if it helps

**Comment by J-D-K** [comment]
It will. I'm gonna be busy today, but I'll try to get something slapped together to get a rough idea of what's up.

**Comment by J-D-K** [comment]
@NimrodMiki @fennectech 
Sorry it took a while. It's been pretty crazy and stressful for me lately. Run this, highlight Skyrim, and open the title info panel for me. Take a screenshot or just type what it says for Size and Max Size. You can also try restoring Skyrim and copy pasting the log for me here. It should write the sizes out as it goes, but `fsFSGetFreeSpace` doesn't seem really reliable for some reason. It should at least help, I hope.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/7166778/JKSV.zip)

**Comment by fennectech** [comment]
My switch should be comming back from getting the SD FPC replaced soon :)

**Comment by J-D-K** [comment]
Any word on the repair yet?

**Comment by fennectech** [comment]
Not yet.  They said they will likely pull it for repair today or tomorrow.   But eh. I’m up to their whims on that.

**Comment by fennectech** [comment]
So testing is not needed any more?  My console arrived with a non functional EMMC.   I’m got a new one coming in the mail

**Comment by NimrodMiki** [comment]
Im going to test it soon, thank you @J-D-K

**Comment by NimrodMiki** [comment]
I had a chance to try it. The last files the program restores still gets corrupted. It helps if i reduce the number of saves then restore it.

**Comment by J-D-K** [comment]
Do you mind sharing the save with me? I was working on something else and someone unintentionally gave me the data required to create Skyrim's save so while I don't have the game, I can at least check it out myself a little.

**Comment by J-D-K** [comment]
So, according to what JKSV just spit out, Skyrim is probably extending its save as it goes:

> The Elder Scrolls V: Skyrim
> 	Save: 0x2800000
> 	Save Max: 0x1E000000

That last build should work if the auto-extending code is kicking in right. Extending manually and punching in like 512MB should do it too.

**Comment by benisai** [comment]
Same here. Skyrim is corrupt. It will load the game but when I go to leave a place or building the game closes out.
