### ISSUE TITLE
App seems to crash everytime in applet mode

### ISSUE THREAD

**Issue by JonJaded** [J-D-K/JKSV#126]
**Describe the bug**
Crash when attempting to open the homebrew app in applet mode 

**To Reproduce**
Attempt to open the nro in applet mode

**Screenshots/Crash code/Crash reports**
Program ID: 010000000000100D
[crash_reports.zip](https://github.com/J-D-K/JKSV/files/7149280/crash_reports.zip)

**App Version**
09.01.2021

**System Firmware Version and CFW Version**
 - FW 12.1.0
 - Atmosphère 1.0.0

**SD card format**
FAT32

**Additional context**
The app seems to work fine in full system memory mode (title take over) but always crashes on the loading screen in applet mode. I may have too many titles?

**Comment by J-D-K** [comment]
Applet mode is gonna be really hit and miss in newer versions compared to old ones. It uses a lot more RAM between the glyph caching, buffer textures, and changes to data that is loaded and stored. There are a few things I could do to cut it down, but I doubt it's going to make that much of a difference.

**Comment by JonJaded** [comment]
I see, I'll keep this in mind, thanks.
