### ISSUE TITLE
Thank you for everything you’ve done for this community

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#128]
I absolutely love jksv and imo its much better than checkpoint.   Has much more functionality and I’ve found you to be way more amenable to feedback than flagbrew.    The tool is simply the best we have and I’d like to thank you for all the time you’ve put into the tool.    Especialy the many feature requests I’ve made.    I want to let you know that its really appreciated.    I hope to continue helping and I’m always available for testing and such.   :).   (Well.  Once my switch gets back from being fixed at least)

**Comment by J-D-K** [comment]
Thank you. Part of what makes it fun is challenging myself with what people request (if it's reasonable). I'm taking a break besides major fixes or translation releases and I'll be back for more. I try my best, but I don't always have time or want to sit for hours writing and debugging stuff.

I bought copies of Xenogears and Vagrant Story about a year ago and never got to play Vagrant Story. They were on my bucket list of Squaresoft games I missed out on as a poor teenager. I also finally got my hands on a Super NT, so I'm looking around to sell my hoard of SNES consoles. A couple of them are 1CHIP revisions and nobody locally wants to pay what they're worth or cares that I replaced the capacitors in a couple of them. 

Also, about that connector on your Switch motherboard. Are you sure it's the connector that's broken? Around the time I wrote Freebird, I replaced the paste to help with the heat from overclocking and somehow borked the SD reader itself. I have a microscope so I could see the connector pins were fine. You can get aftermarket chinese readers for about $6 USD and they work fine.

**Comment by fennectech** [comment]
It was Definitly a broken FPC. One of the metal retainers had fallen off.  . And i hope you enjoy your games.   Enjoy yourself

**Comment by fennectech** [comment]
![image](https://user-images.githubusercontent.com/11953665/134277028-5a3857b2-626b-4de2-af81-3bc0787dffef.jpeg)
