### ISSUE TITLE
Add a lock to prevent accidental deletion

### ISSUE THREAD

**Issue by sleepypikachu** [J-D-K/JKSV#13]
Deleted a save in error (X v.s. Y on Xbox and Switch controllers 😬). Would be nice if I could enable a setting where I have to hold A for 5s to delete or something like that.

**Comment by J-D-K** [comment]
Do you mean in the backup/folder menu or the file browsing mode? Sure, I'll do it.

**Comment by sleepypikachu** [comment]
Not sure what the view is called, open JKSV, select game, pick save folder. Just felt a bit easy to accidentally deleted the folder. (Luckily FAT32 FS means it was not so hard to recover!)

**Comment by J-D-K** [comment]
I added it if you wanna check it out. I'll attach it here. I still need to go through everything and double check, but deleting has a 3 second or 180 frame hold before it accepts for sure
[JKSV.zip](https://github.com/J-D-K/JKSV/files/4396486/JKSV.zip)
.

**Comment by sleepypikachu** [comment]
Thanks for the speedy reply! I will give this a go tonight!

**Comment by sleepypikachu** [comment]
This is great! Very impressive, thank you!
