### ISSUE TITLE
save not restoring

### ISSUE THREAD

**Issue by hotkamote** [J-D-K/JKSV#135]
Hi 
having issues restoring my saved files on acnh, it just keeps loading whatever last island i used.

**Comment by Pachycephalosauria** [comment]
Any luck? Been having the exact same problem.

**Comment by MarleyLua** [comment]
same problem

**Comment by hotkamote** [comment]
still no luck. i think i redid this 10x and nothing.

**Comment by Pachycephalosauria** [comment]
Hi... haven't found a fix, but rather an issue here. so! If you restart your island, and edit the save then reload it... it works absolutely fine! It will load!
However, if you use an old save (in my case, I forgot to backup my original save; so it was from January this year) and edit it, then try to reload it; it simply won't work. I can't figure out why, but I think if you're able to downgrade animal crossing and slowly make your way back up to the current version, save, then edit it then reload... it should work, but I'm not sure if that's do-able as I haven't done that. My main island is on my switch lite, so I don't have anything to lose when resetting on my hacked switch.

**Comment by hotkamote** [comment]
I may have a temporary workaround that works for me but you have to redo it
when it stops working.
I upload my save file to google drive and redos load and unzip before
transferring. It’s tedious but it has been working for me.

**Comment by MarleyLua** [comment]
i'm using Checkpoint as a temp solution, i just passed the edited files of the JKSV folder to checkpoint and restored them using that app, works for now c:

**Comment by J-D-K** [comment]
Does animal crossing have some kind of backup save? Like an extra just in case the first is corrupted?

See, if JKSV can't open the source or destination file, it will bail and you shouldn't see the little dialog with the progress bar. What also doesn't make sense is that as long as there is something to restore in the folder or zip, JKSV will wipe the current save before importing the one from the SD card, so having your old island shouldn't really happen unless Animal Crossing has some sort of fall back. Editing your save can possibly cause issues too.

I don't actually own the game or know much about it. I just found out JKSV supported it without doing it on purpose. It's the truth.

**Comment by 877dev** [comment]
> i'm using Checkpoint as a temp solution, i just passed the edited files of the JKSV folder to checkpoint and restored them using that app, works for now c:

Hmm how does that work? I copied them into Checkpoint folder but now it fails to load...Maybe some file/folder naming requirement?
