### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by impeeza** [J-D-K/JKSV#136]
Hi, first, thanks a lot for all your work

I am on Windows 10 
Just Download MSYS2 (msys2-x86_64-20210725.exe)
Follow installations instructions of https://devkitpro.org/wiki/devkitPro_pacman
Installed the packages:
- switch-dev
- devkitA64
- devkitpro-pkgbuild-helpers
- libnx
- switch-tools
- switch-mesa
- switch-libdrm_nouveau
- switch-sdl2
- dkp-toolchain-vars

Then as stated on OP Readme.md (Requires switch-freetype, libpng, zlib, libjpeg-turbo, lib-curl, and lib-json-c) I did installed the packages:
- switch-freetype
- switch-libpng
- switch-zlib
- switch-libjpeg-turbo

I didn't find switch-lib-curl nor switch-lib-json-c, so installed:
- mingw-w64-x86_64-curl
- mingw-w64-x86_64-json-c

**********************************
  Are this packages correct?
**********************************

Cloning the repository using:  `git clone --recursive https://github.com/J-D-K/JKSV.git`
and run `make`, All start to work fine but at end get the error:

> 
> ...
> file.cpp
> zip.cpp
> fsfile.c
> built ... JKSV.nacp
> C:/msys64/home/Impeeza/JKSV/src/gfx.cpp:5:10: fatal error: SDL_image.h: No such file or directory
>     5 | #include <SDL_image.h>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: gfx.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make: *** [Makefile:152: build] Error 2

******************************************
What package includes the SDL_image.h?
******************************************

I did try to install:
- mingw-w64-x86_64-SDL_image
- mingw-w64-x86_64-SDL2_image

but no luck

Thanks for your help.

**Comment by impeeza** [comment]
Update: I did find what the needed packages are:

```
NAME ON README.MD    NAME OF PACMAN PACKAGE
switch-freetype      switch-freetype
libpng               switch-libpng
zlib                 switch-zlib
libjpeg-turbo        switch-libjpeg-turbo
lib-curl             switch-curl
lib-json-c           switch-libjson-c
```

For the SDL_image.h that was included on one of the pacman packages:
- switch-sdl2_gfx
- switch-sdl2_image

I just be able to compile the JKSV.nro of the latest master branch (2021/11/11)  but on my

Atmosphere 1.2.4
Hekate 5.6.5
Switch Erista unpatched FW 13.1.0


When invoked from HBL the program closes because an error ;( so I am unable to test it.

**Comment by J-D-K** [comment]
Sorry. I was going to update the readme sometime with the actual pacman commands, but I wanted to capture some tutorial videos too. I just haven't had time to sit down and get it all done.

As for the crash, is it instant, or does it at least make it to the loading screen?

**Comment by impeeza** [comment]
Hi, the crash is instantly, HBL -> JKSV -> black screen -> error

I will try to make a video of the MSYS2 installation (I want to repeat from start to depure all test made)

**Comment by pixeltester** [comment]
This is user error, there is no issue with compiling with a proper environment and there's no crash with the latest version either. Not an issue for JKSV issues.

**Comment by impeeza** [comment]
Will try again

**Comment by impeeza** [comment]
Well, update to my compilation issue:

Clear any traces of MSYS2 on my system, download msys2-x86_64-20210725.exe from MSYS GitHub.
Then I did run MINGW64 environment and the next commands:

```
pacman -Syuu
pacman -Sy --needed --noconfirm git make subversion
exit
```
after run MINGW64 again, start DevKitPro installation, first the Keys:

```
pacman -Syuu
pacman -Syu
pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0
pacman -U https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz
```

Then setup pacman for install devKitPro packages 

```
nano /etc/pacman.conf
```

and add the next at end of the file:

```
[dkp-libs]
Server = https://pkg.devkitpro.org/packages

[dkp-windows]
Server = https://pkg.devkitpro.org/packages/windows/$arch/
```

restart MINGW64 and setup environment variables:

```
pacman -Sy
pacman -Syu

export DEVKITPRO=/opt/devkitpro
export DEVKITARM=/opt/devkitpro/devkitARM
export DEVKITPPC=/opt/devkitpro/devkitPPC
```

Install base packages


```
pacman -Syu


pacman -S --needed --noconfirm switch-dev devkitA64 dkp-toolchain-vars libnx switch-tools switch-mesa switch-libdrm_nouveau switch-sdl2
source $DEVKITPRO/switchvars.sh
```

Then install packages needed by JKSV

```
pacman -S --needed --noconfirm switch-freetype switch-libpng switch-zlib switch-libjpeg-turbo switch-curl switch-libjson-c switch-sdl2_gfx switch-sdl2_image

pacman -Syu
```

Clone the repository and compile it:

```
git clone --recursive https://github.com/J-D-K/JKSV.git

cd JKSV
make -j
```

The resultant set of files are:

![image](https://user-images.githubusercontent.com/41979604/141728116-bf1afad2-dac6-4c56-8e4d-cbd0edecc32e.png)

Copying the JKSV.nro file to switch and opening HBMenu, get these details

![image](https://user-images.githubusercontent.com/41979604/141727525-1ac6a9d3-f234-4db1-962b-81cf6e63845a.png)

after running it I get the error  "The software was closed because an error occurred."

The folder SD:/JKSV is created and the file SD:/JKSV/log.txt is empty.

Am I using an invalid environment?  missing some step? the generated file is bad file size? my JKSV.nro SHA256 is: 3295a4d48443845e1dcdc6c0210cf6cad6221cee015cd29f0d7776286b97898c.

If I run HBMenu on Applet mode, Atmosphère show the new screen error:
![image](https://user-images.githubusercontent.com/41979604/141728904-71835bfb-601b-48df-b3e4-3d9b71455e4b.png)

On this case, The folder SD:/JKSV is created and the file SD:/JKSV/log.txt is empty too.


My Setup:
Hekate 5.6.5
Atmosphère 1.2.4
Firmware 13.1.0
Sigpatches generated with AutoIPS
Erista V1 unpatched

I know this is not a support channel, but I want to be sure about compiling in order to help with new releases.

**Comment by pixeltester** [comment]
I have no idea why you're getting that error, I use the latest version of everything and a compiled version of JKSV master works perfectly as of the latest commit. In fact I've never had a broken version of JKSV from master. Fix your Switch homebrew environment.

Also I don't know why you think the JKSV issue tracker is the place to ask for guidance to set up a full Switch development environment? The most you should be expected to be provided with are the required packages.

**Comment by J-D-K** [comment]
[JKSV.zip](https://github.com/J-D-K/JKSV/files/7541570/JKSV.zip)
Does this run for you? It's identical to what I have currently. If not, it will log where it gets stuck. If you're on Windows, I'm pretty sure you can just use the devkitPro installer and all should be fine as far as I know.

**Comment by impeeza** [comment]
As I have stated I know is no the place for support, but it started as a legit issue because the documentation have the bad names of packages, I will test the attached compilation, and follow the guidance.

thanks a lot.

**Comment by impeeza** [comment]
HI, the one attached by JDK works fine,  I will be making more test and let you know, regards.

by now i will close the issue, knowing JDK has put on the to do list to put the correct names of packages. 

regards from Colombia.
