### ISSUE TITLE
Latin American Spanish Translation

### ISSUE THREAD

**Issue by impeeza** [J-D-K/JKSV#137]
Hi, Hope it works, I made the Translation for Latin-America Spanish (419); It could be a start for Spain Spanish too.
[es-419.txt](https://github.com/J-D-K/JKSV/files/7516606/es-419.txt)

**Comment by J-D-K** [comment]
So, unfortunately (entirely my fault), I tweaked some strings and the files included in the repo are slightly out of date. Some things are broken and will need some small tweaks once I finish up. Ex:
![2021111318371700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/39171744/141662099-2bde700a-c79f-4cdc-85c2-2e3e39bc6a87.jpg)
Again, sorry. I had to rush some stuff before the last release because of time with the intention of fixing later. I'm happy people are eager to translate, but it does create some problems now and then.

**Comment by impeeza** [comment]
Don't worry. Tomorrow will see deeper in it and try to make work.  Today i did try to compile the last version but messed up my msys2. Try again tomorrow. Thanks for your help

**Comment by impeeza** [comment]
Hi, I has been playing with the translation, make some improvements.  For now the major incidents are:

The name of "Device" on the left menu, is Shifted to the left, and as in Spanish is "Dispositivo", more length than original, I did try to change to: "Disposi-\ntivo" trying to use two lines, but now boot lines are trimmed.

The one you point about the Title ID, when using English the data is showed fine:
![image](https://user-images.githubusercontent.com/41979604/142748080-1e1bc49d-7ade-48a1-a80a-39b2f2279030.png)

But when using the translation, nothing is showed, I wish to know how to help you but my programming skills are limited, on Spanish is show:
![image](https://user-images.githubusercontent.com/41979604/142748104-22908c58-461d-4e03-acbd-99204d76a0e2.png)

I did modify the file to match the names showed on English language and add some improvements.

By the Way, What is "Export SVI"?

The newest version of file is:
[es-419_2021_11_20.zip](https://github.com/J-D-K/JKSV/files/7575700/es-419_2021_11_20.zip)

Let me know if I can help with anymore.


An enhance what could be added on the future could be, change the behavior of the option  "Settings" -> "Force English To Be Used: " to select the language of the interface.  By Example, I like all my games on English and the Switch interface on English, but I like JKSV on Spanish.

Regards.

**Comment by J-D-K** [comment]
Export SVI exports a file that can be used to create save data on other systems for games you don't own or have installed totally legally on your emunand but not on sysnand. I guess Smash has some bonus for having Kingdom Hearts save data. I know Tales of games do it too on other systems.

I'm aware of the issues and I'm using your translation to try to fix them or come up with a solution. I can't really push anything right now without pushing the google drive code and it's not ready.

**Comment by impeeza** [comment]
Thanks a lot, don't worry let me know if I can help.

P.S. on the 3DS the Professor Layton collection make use of previous games save data and if is present the give you Bonus DLC for free.  cool addition to JSKV be able to import/Export that type of save data.

**Comment by J-D-K** [comment]
I'll be taking a closer look soon. I'll get something straightened out, I promise. I'm trying to get 3DS somewhat up to Switch levels and it isn't going as easy as I'd hoped. I try not to ignore people but I only have so much time after work.

**Comment by impeeza** [comment]
Don't worry. Lemme know if there is anything I can help with

**Comment by impeeza** [comment]
With the professor Layton reference. I mean to be able to "restore" a save game for a game you don't have installed. Some games will use save games for another games in order to give you rewards

**Comment by J-D-K** [comment]
Just gonna close this. It's working fine now.

Just trying to sort out what needs to be looked at and what doesn't.
