### ISSUE TITLE
Can't find "Export SVI"

### ISSUE THREAD

**Issue by miapuffia** [J-D-K/JKSV#138]
I've searched in every menu/submenu, and I've even searched for all mentions of "SVI" in the code, but I can't find the option to export as SVI. Am I missing something, or is the README out of date and that feature no longer exists? Thanks.

**Comment by J-D-K** [comment]
It needs to be built from source for that currently, it was a recent addition. Here. I can't really give it a test run though, because old builds will destroy my drive config.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/7612151/JKSV.zip)

**Comment by ToxiClay** [comment]
With reference to the SVI feature, we have confirmation that it performs as advertised in the wild.

https://www.reddit.com/r/SwitchPirates/comments/y9t0ym/injecting_saves_for_games_i_dont_have_installed/
