### ISSUE TITLE
v11.15.2021 Empty Title Information

### ISSUE THREAD

**Issue by muxi1** [J-D-K/JKSV#139]
Hello JK,
Concerns version 11.15.2021:
The output of Title Options --> Information is empty.
Is there a possibility to fix this?
Thanks in advance

**Comment by J-D-K** [comment]
Turn on the Language Override option, press plus to exit and reopen. It should force it to use the internal strings for now.

**Comment by muxi1** [comment]
Thank you, that was helpful!
