### ISSUE TITLE
Can not hit "new" it freeeze for 5 seconds. 

### ISSUE THREAD

**Issue by ulao** [J-D-K/JKSV#141]
I'm trying to back up from device. When I open a game (Animal crossing for example) I get only a "new" option but hitting it does not do anything but freeze the interface up for 5 seconds. Same for mariokart... How can I get the keyboard up to save my data? I tried 5 versions ok jksv  with the same issue.

**Comment by J-D-K** [comment]
You're using the album? You need to start with title takeover, or you can hold R and press A to bypass the keyboard completely.

**Comment by skunx99** [comment]
whoa, now I feel like I'm really stupid.. No idea what that means or why I need to do it. But fair enough!f
What is a take over, I see no options for this in jksv?

**Comment by skunx99** [comment]
LOL, by accident I held L and pressed A, and it worked...That was so confusing...
