### ISSUE TITLE
Option to save all (Y) not available

### ISSUE THREAD

**Issue by JaySea77** [J-D-K/JKSV#142]
I have been using JKSV to make a backup of all saves for all users with also bcat and system saves.
The latest version should have this function with the Y button, but it is not available nor will the Y do anything.

Am I doing something wrong or is this function removed?

**Comment by J-D-K** [comment]
It had to be reworked. It's back if you build from source or I can build it for you later.

**Comment by JaySea77** [comment]
No problem. If it is a known issue I will see it in next release :)
