### ISSUE TITLE
Not starting on fw 13.2.0 Atmosphère 1.2.5

### ISSUE THREAD

**Issue by Conan179** [J-D-K/JKSV#143]
Hello on my switch fw 13.2.0 Atmosphère 1.2.5 no emunand fat32, jksv dont lounch, no black screen, no error message, the switch simply jumps back to the hbmenu

**Comment by J-D-K** [comment]
The last time this happened that I remember, it was because the config got corrupted somehow. Are you using the last release or did you build the source?

**Comment by Conan179** [comment]
I suing the nrto from the reelase site: https://github.com/J-D-K/JKSV/releases/tag/09%2F01%2F2021

**Comment by Conan179** [comment]
-.- the config file sdmc:/config/JKSV/JKSV.cfg was defective, I deleted a blank line, now it works again.
I'll attach both, maybe that will help you.
[jksv config files.zip](https://github.com/J-D-K/JKSV/files/7687643/jksv.config.files.zip)
