### ISSUE TITLE
Problem with folder permissions

### ISSUE THREAD

**Issue by kimtiago** [J-D-K/JKSV#146]
Hi,

i did the backup of my saves with JKSV, after that, i copied the folder to my windows computer and formatted the sd card.

i installed all games again and copied the JKSV folder to the right place...

when i tried to restore de saves to the games, none of the backups are showing, and when i tried to backup a new save, the file isn't save in the folder...

if i delete the folder and let JKSV create by himself, i can backup the saves...

i think is something with the JKSV folder permissions, but i didnt figure out the true reason...

any ideias?

**Comment by J-D-K** [comment]
Sorry it took a while to get back to ya. I don't believe the switch actually uses any of the permissions passed to mkdir, which I assume is just a wrapper to fsFsCreateDirectory. Without being able to see for myself what your SD card looks like, I don't really know what to tell you.
