### ISSUE TITLE
GDrive - creates directory but doens't upload files

### ISSUE THREAD

**Issue by Apicedda** [J-D-K/JKSV#147]
I built the latest version from source and setup gdrive. It connects correctly when starting JKSV, but making a new backup doesn't upload anything on drive other than the JKSV folder and the game folder inside it. log.txt looks empty, any other way to know what's going wrong?
Credentials are correct since i tried them with tinfoil and it reads and uploads correctly.
I tried naming the backup without spaces and symbols, no difference

**Comment by J-D-K** [comment]
You have to highlight the backup in the folder list and press ZR and it will be uploaded.

**Comment by Apicedda** [comment]
ok, I'm dumb, seeing the folders i thought it would upload the save data too.
Btw the app crashes if opened with airplane mode, but you probably know this already.

Thank you

**Comment by J-D-K** [comment]
It wouldn't be hard to add an auto upload or something in the options. I can't right now cause a family member is sick and I'm helping when I can. 

Thanks for letting me know about the crash! I'll get it straightened out.

**Comment by Apicedda** [comment]
No worries, take care of your family
