### ISSUE TITLE
Feature request: WebDAV storage

### ISSUE THREAD

**Issue by ShadwDrgn** [J-D-K/JKSV#148]
Would be AWESOME if we could have it save to a webdav location similar to how it can currently use google drive. Many many services offer webdav including nextcloud (a common hosted filesharing service like dropbox). If I could backup directly to my nextcloud account then it would be easy to sync saves on yuzu on my PC.

**Comment by J-D-K** [comment]
I still need to finish up the drive support before I would consider anything else. Everything I wrote for drive is also very portable. I actually wrote it on Linux first before moving to Switch. It wouldn't be difficult for someone to use the code and make an auto-sync app is what I'm getting at.

**Comment by rado0x54** [comment]
Hey @J-D-K I've added a PR #207  for Webdav support. The PR puts the Webdav implementation and the Google Drive implementation behind a common interface. Would love to get this merged.

@ShadwDrgn I'd love to have you test it. Thanks!

**Comment by GrayXu** [comment]
custom webdav is much better than google drive
