### ISSUE TITLE
Feature request.  Disable launch in applet mode 

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#149]
The reason is if you have alot of titles installed the application always crashes on startup (OOM)   It would be nice to have a toggle option to prevent the app from starting in applet mode to prevent the fatal crashes.

**Comment by J-D-K** [comment]
It was gonna get blocked anyway. The browser can't start in applet mode to log in to Google.

**Comment by J-D-K** [comment]
Added a warning. Might be completely disabled in the future.
