### ISSUE TITLE
[Feature Request] Option to favorite most used titles

### ISSUE THREAD

**Issue by Elionna** [J-D-K/JKSV#15]
Great work with this app, it has replaced checkpoint as my save management tool, one thing I would like is the ability to favorite titles so they appear at the top of the list for quick backups

**Comment by J-D-K** [comment]
The latest pre-release version has this. Press minus while a title is highlighted and it'll be pushed to the top of the title list. Unless, you mean something else?

**Comment by Elionna** [comment]
that's exactly what I meant, thank you!
