### ISSUE TITLE
Deleted ACNH saves still showing up in JKSV folder

### ISSUE THREAD

**Issue by ohheplays** [J-D-K/JKSV#152]
I couldn't find anyone else with this issue, but I have several saves that I deleted from the app on my switch, but when I connect to  my SD card, the folders for the deleted saves still show up but when I open them I get this error: 

"550 no such file or directory"

I am also having this issue with my most current ACNH save. I can still load it and play the game but when trying to get into the folder on my computer, I get the same error from above. 

Thank you in advance and sorry if this has already been answered somewhere - I tried to find a solution but could not.

**Comment by ohheplays** [comment]
I also have an issue where one save that I deleted in the app still shows up in JKSV, but there is no folder for it in the JKSV folder on my sd card, but there is a folder with the save name in my root folder, which also gives me the same error code above ^ 

meant to include this in the original post

**Comment by J-D-K** [comment]
I'll get back to you as soon as I can to try to figure out what's going on. Later today after I'm home.

**Comment by ohheplays** [comment]
let me know if theres anything else I could provide that would help!

**Comment by J-D-K** [comment]
Sorry. I need to finish up some things first. I also had something come up so I didn't get a chance to do much yesterday.

One thing I can tell you is that if you have the trash bin feature enabled and you try to trash something with the same name, it will fail and leave the folder/zip sit.

I promise I'll get back to you as soon as I can.

**Comment by J-D-K** [comment]
OK. I added some basic logging to the delete function to get a rough idea of what's up. It'll output a little info(paths) to the log.txt in the JKSV folder. Paste it here to rule that stuff out and I'll log more if I need to when I have more time.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/8328074/JKSV.zip)

**Comment by ohheplays** [comment]
I actually already tried fixing archive bits before posting but it didn’t change anything. 

I actually was finally able to just delete the folders without the error coming up and have been using everything like before without problems for the last two or three days, so not really sure what changed? But I appreciate your time and all your help!

**Comment by fennectech** [comment]
Sounds like it could be filesystem corruption then :|. If this happens again. Do a disk check and delete the directories in windows
