### ISSUE TITLE
not prompted to login to google

### ISSUE THREAD

**Issue by Neoakb** [J-D-K/JKSV#155]
I have set up the API credentials and confirmed they work via tinfoil. 

I added the lines to my config file. I opened JKSV via a game, not the applet. I have BrowseNX installed. 

It seems to change the save location to my secret, and doesn't prompt to login.

I am on the recently released updates for the system, atmosphere, and other applications.

**Comment by J-D-K** [comment]
Just so I'm clear here, you mean it's setting the working directory to your client secret in the config?

**Comment by Neoakb** [comment]
Correct

if I have the two lines for the code and the secret and then open JKSV,
it'll change the working directory to the secret and remove both lines from
the bottom.

**Comment by J-D-K** [comment]
Ok, so I think you're using the release version. To use drive right now you need to build the source. I didn't plan on it taking this long to release a new build but I caught covid in the beginning of the year and got backed up at work pretty bad.

I'll be around later to build it for ya if you need it.

**Comment by Neoakb** [comment]
I was able to build it and it connected to google drive, but it crashes
whenever I try to make a backup. I'm launching it fully, not through the
applet hbmenu.

Could I try a build of yours?

Thanks

**Comment by blitz2kx** [comment]
> Ok, so I think you're using the release version. To use drive right now you need to build the source. I didn't plan on it taking this long to release a new build but I caught covid in the beginning of the year and got backed up at work pretty bad.
> 
> I'll be around later to build it for ya if you need it.

Hey any chance a working build with GD support is available? Ty in advance.

**Comment by J-D-K** [comment]
I'll be back later and build the git code. The lastest build I have has some unfinished updates and improvements that make it a little unstable.

**Comment by J-D-K** [comment]
Here it is. It's still all manually done in this as far as I remember. I think mine is the only one that has the config option at the moment to automatically do it. Press ZR to upload what you want once you're logged in. As a side note, Google recently emailed me and said they're going to stop allowing the authentication method I used later this year unfortunately.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/9033915/JKSV.zip)
