### ISSUE TITLE
No saves and no data in jksv after 1.14 update

### ISSUE THREAD

**Issue by DarkRaGaming** [J-D-K/JKSV#156]
I do have save from pervious backup . 

![unknown-2.png](https://user-images.githubusercontent.com/49731556/162139665-444d28a7-5772-4d7f-8f68-30326c76139b.png)

![unknown-3.png](https://user-images.githubusercontent.com/49731556/162139672-0b3694f8-0a5d-4acd-854e-9a30b02fec0b.png)

When i do go into the jksv it shows all empty and no saves. I even tried to save and nothing happens . 

![20220406_235203.jpg](https://user-images.githubusercontent.com/49731556/162139939-6e0004b1-e087-4d8d-905b-43f4f0cabeac.jpg)

**Comment by DarkRaGaming** [comment]
I was able tp get savw but it will not load save

**Comment by J-D-K** [comment]
I'll be back soon. Sorry, but my glasses broke and I can't see unless I squint and basically have my face against my screen.

**Comment by DarkRaGaming** [comment]
> I'll be back soon. Sorry, but my glasses broke and I can't see unless I squint and basically have my face against my screen.

Alright. I was able to get saves to happen but unable to restore the saves.

**Comment by DarkRaGaming** [comment]
When restoring it auto creates a backup only does this with older saves. 

![20220416_134154.jpg](https://user-images.githubusercontent.com/49731556/163690764-6df8db71-fa52-458f-8221-cffaae7bb236.jpg)

**Comment by DarkRaGaming** [comment]
Further looking found a reddit post about setting for JKSV could cause this issue. And found out I don't have a Config file.
