### ISSUE TITLE
Crash and unusual behavior when restoring a backup with a "%" in the folder name

### ISSUE THREAD

**Issue by n00neimp0rtant** [J-D-K/JKSV#157]
Steps to reproduce:

1. Enter JKSV and backup a save
2. Edit the name of the save directory to contain a "%"
3. Enter JKSV again and attempt to restore the save

Observe that the text is clipped starting at the % symbol. JKSV crashes while holding the restore button.

[01651791474_010000000000100d.log](https://github.com/J-D-K/JKSV/files/8606485/01651791474_010000000000100d.log)

**Comment by pixeltester** [comment]
>     2. Edit the name of the save directory to contain a "%"

**Why?**

That's an issue with the Switch filesystem and not JKSV.

**Comment by DarkRaGaming** [comment]
> 
> >     2. Edit the name of the save directory to contain a "%"
> 
> **Why?**
> 
> That's an issue with the Switch filesystem and not JKSV.
> 

I was also having issue with restoring since newest switch update

**Comment by fennectech** [comment]
Did you create this save on the swtich?  Or is it something you imported?

**Comment by n00neimp0rtant** [comment]
> Did you create this save on the swtich?

No, I renamed it on my computer, then synced it back.
