### ISSUE TITLE
I Am Setsuna Leaves a trailing period

### ISSUE THREAD

**Issue by damien-crypto** [J-D-K/JKSV#159]
I Am Setsuna Leaves a trailing period on the folder name the causes Issues with Windows copying/deleting/opening or doing anything with it.

If anybody can repeat it or maybe its just me

**Comment by fennectech** [comment]
Definitly something that needs to be corrected.  Not a “Just you” thing

**Comment by J-D-K** [comment]
Ok. I don't know when I'll get to it. I swear I had that game at one point and I don't remember having problems. Maybe I changed something?

**Comment by J-D-K** [comment]
I took a look just now, and it seems the Switch version is missing the function 3DS has to remove trailing periods from the titles. I thought it did...

**Comment by J-D-K** [comment]
So, I'm starting off again using the master branch. I've double checked that I didn't change the export folder to be sure and I am Setsuna definitely has the trailing `.` stripped off for me. I'm going to investigate more, but is your Switch set to a region/language besides English?

**Comment by damien-crypto** [comment]
My switch is set to english and US.

The trailing period is on the folder name not the file if I recall correctly. 
There is another one I found that does it too. 

I will double check and get back to you

**Comment by fennectech** [comment]
Can you delete the directory and back it up again and see if it still has it?

**Comment by J-D-K** [comment]
This was a problem on 3DS with Super Smash Bros. IIRC. I looked around and found it in a different place, but the code is there. It's possible they updated the game and changed the title to use a unicode character at some point though. I'm just using the base game dump from my non-hacked Switch.
