### ISSUE TITLE
Allow disabling of hold to overwrite

### ISSUE THREAD

**Issue by Ry3yr** [J-D-K/JKSV#16]
Add "disable of hold A to overwrite save" option to settings.
For those that can spell redundancy in their dreams.

**Comment by J-D-K** [comment]
Ok

**Comment by J-D-K** [comment]
Here. I changed the config to use bits too, so you might need to delete the cfg.bin file in JKSV's directory if it acts funny at all. Let me know if that does it for ya.
[JKSV.nro.zip](https://github.com/J-D-K/JKSV/files/4477062/JKSV.nro.zip)

**Comment by Ry3yr** [comment]
Works perfect !

Thanks for adding that :)

- Pascal

2020-04-14 20:36 GMT+02:00, JK <notifications@github.com>:
