### ISSUE TITLE
The device archive cannot be exported when the device is in Chinese(设备)

### ISSUE THREAD

**Issue by Travisss** [J-D-K/JKSV#160]
The device archive cannot be exported when the device is in Chinese（设备）
Version is 09.01.2021
It is recommended to change the "设备" to "device" in Chinese

**Comment by Travisss** [comment]
I use Google translate, and looking forward to your reply

**Comment by fennectech** [comment]
This could have something to do with FAT32 not supporting Unicode

**Comment by Travisss** [comment]
> This could have something to do with FAT32 not supporting Unicode in file names

My sd card is in exfat format. I guess this is because the file system of ns does not support Chinese file names. 
jksv tried to create a new directory named “设备” and failed, so the device archive could not be exported。
When I turn on “force english to be used”, I can export device archive successfully
Or when I customize the plain English catalog when exporting individually, the device archive can also be exported successfully。But the default export directory contains devices
And the 08.01.2021 version I use can successfully export the device archive。The default export directory for this version is “Device Saves ...”

**Comment by J-D-K** [comment]
Ok, so what I think is happening is that the newer version must be using the translation file's string for `Device` and since it is in Chinese, it fails. It isn't a difficult fix, but I can't get to it right now.

**Comment by Travisss** [comment]
> Ok, so what I think is happening is that the newer version must be using the translation file's string for `Device` and since it is in Chinese, it fails. It isn't a difficult fix, but I can't get to it right now.

Thank you very much for your reply, looking forward to your next update to fix this problem

**Comment by J-D-K** [comment]
Sorry it took so long. I'm still reading through everything, it's been a while, but I do believe I was correct earlier. The system user accounts sort of bypass the ASCII check that normal ones go through to prevent this. So, instead of being turned into `AccXXXXXXXX`, it's just passing through the translation's string for Device. Fix incoming once I figure out how I want to handle it.
