### ISSUE TITLE
Settings Not Sticking

### ISSUE THREAD

**Issue by TrueTexan21** [J-D-K/JKSV#163]
Whenever I close JKSV, settings revert. Particularly the function that causes the system to create a new auto save whenever you restore a save. This is happening on two devices.

**Comment by fennectech** [comment]
Use + to close the app.  Not the home button Sent from my iPadOn Nov 8, 2022, at 9:34 AM, TrueTexan21 ***@***.***> wrote:﻿
Whenever I close JKSV, settings revert. Particularly the function that causes the system to create a new auto save whenever you restore a save. This is happening on two devices.

**Comment by J-D-K** [comment]
Yes, remember to press + to exit instead of through the home menu. Maybe I'll update it to save config when something is changed later. On 3DS, this wasn't a problem because closing the CIA releases through home still allowed the app to shutdown properly.
