### ISSUE TITLE
SaveCreate Failed -> 402

### ISSUE THREAD

**Issue by ItzakW** [J-D-K/JKSV#165]
Hi, thanks for your JKSV. When I'm going to backup my save files in SX OS, it comes out something wrong with the log showing "SaveCreate Failed -> 402". What can I do to fix it?

**Comment by J-D-K** [comment]
That error means that you tried to create a new save container on the system for the game, but it already exists and failed. To make a backup, just press A with the icon highlighted. X is a bunch of extra options. The core stuff is just pressing A.
