### ISSUE TITLE
Add ability to "delete" system saves (on device)

### ISSUE THREAD

**Issue by Ry3yr** [J-D-K/JKSV#17]
As I have not seen any tool that could do it.

Could it be added to allow JKSV to "delete saves stored on the Switch itself" aswell ?

Maybe protect this feature with the konami code or something, to stop sob-stories from unfolding.

**Comment by J-D-K** [comment]
Do you mean the system save data, or the save data on the system? Technically it already can if you mean the latter. In file mode, press X on the first `.` on the list and select delete. It'll delete the root of the save. Adding it to a button wouldn't be hard, but people used to complain a lot about it on 3DS because they didn't understand what I meant.

**Comment by Ry3yr** [comment]
Yes save data on the system.

A button would rock.

Am Mittwoch, 15. April 2020 schrieb JK <notifications@github.com>:

**Comment by J-D-K** [comment]
Here ya go.
[JKSV.nro.zip](https://github.com/J-D-K/JKSV/files/4482757/JKSV.nro.zip)

**Comment by Ry3yr** [comment]
Hmm, ok, maybe I'm just being stupid now.
Pressing X is possible as you said,
however I fail to find a listing of savegames as in (see attchment)
NXplorer for example.

Am I missing something here ?

2020-04-15 19:27 GMT+02:00, JK <notifications@github.com>:

**Comment by J-D-K** [comment]
I'm not seeing an attachment. Do you mean the save archives themselves? The files on the user partition named with a hex string?

**Comment by Ry3yr** [comment]
Not quite.

More like this: https://i.ibb.co/6FzLs62/IMG-0219.jpg
(As I said, NXplorer lists the saves on device [but I cannot interface with
 them.])

Hex Strings won't help much, as noone knows by heart which hex string goes
with which game.

Am Mittwoch, 15. April 2020 schrieb JK <notifications@github.com>:

**Comment by J-D-K** [comment]
OK, I'll take a look later. Actually, there is a way to connect the hex strings to specific games IIRC. I just couldn't find room to display it.

**Comment by J-D-K** [comment]
Is this what you mean? I added it to the title selection. Pressing ZR will remove the save from the system. I'd still need to add a rescan though. The changes won't be shown unless you restart JKSV.
[JKSV.nro.zip](https://github.com/J-D-K/JKSV/files/4483707/JKSV.nro.zip)

**Comment by Ry3yr** [comment]
If by "this" you mean that "[ZR \ 'Erase'" button, then:

Yes.


However as said already, blindly deleting hexadecimal folders will not
yield any certainty.
(See:  https://i.imgur.com/6VaABoT.jpg)

So I suppose it is imperative to add correct naming.

(Since https://github.com/CompSciOrBust/N-Xplorer has proper naming
implemented, maybe moving from there is a quick way to success ?)



2020-04-15 22:57 GMT+02:00, JK <notifications@github.com>:

**Comment by J-D-K** [comment]
I'm not blindly deleting anything. I'm use a system call with info retrieved from the system to delete the archive from the user partition. Those are system save archives from the system partition and some of them contain really important files. I'm not going to enable deleting those. They're needed by the system.

**Comment by Ry3yr** [comment]
Then we are talking about diffrent things I presume ?

As already stated,
I'm talking about "system /savegames"
i.e. -> savegames created when running any kind of gamecard /
downloaded eShop title.

Those are the ones I'm after.

So where can one find these ?

2020-04-15 23:38 GMT+02:00, JK <notifications@github.com>:

**Comment by J-D-K** [comment]
You're talking about these one the left, right?
![2020041517481600-F8D087CFC849713C76A06A954E9486D3](https://user-images.githubusercontent.com/39171744/79392509-7e7dd900-7f41-11ea-9fcc-5eb6f0106447.jpg)

**Comment by Ry3yr** [comment]
I sadly can't for sure say these are the ones I'm after, as they are
only bit strings.

As said previously:

These: https://imgur.com/YIwIlkM

are the ones I'm looking for (these are obviously the saves on my system)

I don't know *where* in JKSV they are to be found, however...
they are surely there, as your program allows to *backup *restore
them.

So deleting them should be a possibility aswell I take it ?


2020-04-15 23:50 GMT+02:00, JK <notifications@github.com>:

**Comment by J-D-K** [comment]
I think so. It calls `fsDeleteSaveDataFileSystemBySaveDataSpaceId` and the system deletes the save from NAND. I just didn't get to write a title rescan to show the change yet.

**Comment by Ry3yr** [comment]
Ah.
Perfect :)

Issue resolved!

2020-04-16 0:03 GMT+02:00, JK <notifications@github.com>:
