### ISSUE TITLE
NS 15.0.1 cannot inject payload

### ISSUE THREAD

**Issue by LiangYuJing233** [J-D-K/JKSV#170]
No RCM device detected
RCM Device detected
Invoking TegraRcmSmash.exe with args : "D:\TegraRcmGUI_v2.6_portable\hekate_ctcaer_5.9.0.bin"
TegraRcmSmash (32bit) 1.2.1-3 by rajkosto
Opened USB device path \\?\usb#vid_0955&pid_7321#5&32414a01&0&2#{aa0dbd45-3117-f331-5c49-76bf65225042}
RCM Device with id [id] initialized successfully!
Uploading payload (mezzo size: 92, user size: 105953, total size: 172169, total padded size: 176128)...
Win32 error 31 happened trying to write payload buffer to RCM
Error while injecting payload (RC=-8)
RCM device disconnected

How can I fix this promblem

**Comment by J-D-K** [comment]
This has nothing to do with JKSV.
