### ISSUE TITLE
Change OAuth request for Google Drive

### ISSUE THREAD

**Issue by LeoGeneret** [J-D-K/JKSV#172]
I find a build that supports Google Drive upload and edited the config file.
When I try to upload a save, the webbrowser open to login via Google but a bad_request error 400 appears.

I tried to check the code but it seems that the request has to be updated as the new Google token authorization policies changed few months ago.

Could you update the request ? Google Drive upload is one of the best feature of this homebrew.
Cheers

**Comment by J-D-K** [comment]
The last time I tried it was still working fine. I thought the changes to Google only applied to production apps. I'll take a look and try when I can. It's not going to happen overnight.

**Comment by J-D-K** [comment]
I finally had time and deleted my refresh token from my config. I can still login no problem and everything still functions as it should, meaning the login method still works for apps not in production. I've been told a few times the instructions for drive need to be update which I'll be doing today when I get a chance.

**Comment by J-D-K** [comment]
Now 100% verified that the OAuth is still working. There may have been something wrong with your configuration.
