### ISSUE TITLE
JKSV  error in new version kefir 660 

### ISSUE THREAD

**Issue by suww37** [J-D-K/JKSV#173]
In the kefir 660 version, jksv does not run with an error (2168-0002 (0x4a8)). I think it is not compatible with the new atmosphere version. Please fix.

**Comment by MYFW93** [comment]
Try using this version:

[JKSV_16.0.0_fix.zip](https://github.com/J-D-K/JKSV/files/11404048/JKSV_16.0.0_fix.zip)
