### ISSUE TITLE
Google doesn't popup when activating gdrive 

### ISSUE THREAD

**Issue by LeRatGondin** [J-D-K/JKSV#174]
Hi,
When I start JKSV after I put my config file from google console to sd://config/JKSV (I have built jksv) google does not popup asking for a password , I tried and the config file work normally it's just that google does not popup , it's the same if I launch it without applet mode 
(I don't know if it's related but when i start mtp responder in dbi i can't paste or edit any file) 
Regards

**Comment by J-D-K** [comment]
Is the file name still the same? Ex: client_secret[xxxxx].json? The way it works is it searches for the client_secret in the beginning of the file name. If it's not, just name it client_secret.json and it should pick it up.
