### ISSUE TITLE
Crashing on firmware 16.0.0

### ISSUE THREAD

**Issue by ELY3M** [J-D-K/JKSV#177]
latest atmosphere 1.5.0 and I am on firmware 16.0.0  
I get atmosphere crash screen when I opened this app in homebrew menu.  
I also tried holding R for full Ram and started this app.  It resulted in black "software closed" screen.

**Comment by Goma1337** [comment]
Can confirm, same problem here.

**Comment by ELY3M** [comment]
Please get the zip from this post.    Thank you to SciresM for the fix.  

https://github.com/J-D-K/JKSV/pull/176

**Comment by ELY3M** [comment]
https://github.com/J-D-K/JKSV/files/10809597/JKSV_16.0.0_fix.zip
