### ISSUE TITLE
Issues when restoring on FW 10.0.0

### ISSUE THREAD

**Issue by androo-d** [J-D-K/JKSV#18]
I was accidentally updated to 10.0.0 and even though JKSV did not say anyway that it was officially supported, I tried it with animal crossing. It backups the save fine but when trying to restore it, it says that animal crossing is corrupted. I’m hoping this is a simple issue with 10.0.0 and in a patch I can get my island back.

**Comment by J-D-K** [comment]
Is it just Animal Crossing that does this? I'm not updated yet, but I'll take a look as soon as I can.

**Comment by rafpoop** [comment]
Any update on this? It has been a week now and I just accidentally updated my console and can't use JKSV anymore. Sorry to rush you, just sucks that I can't back up anymore.

**Comment by J-D-K** [comment]
What CFW are you running? I updated to 10.0.1 and haven't had any problems myself.

**Comment by rafpoop** [comment]
You're right, I did a fresh install of everything and it's working fine. Thank you for replying though!
