### ISSUE TITLE
Crash on 02.23.2023

### ISSUE THREAD

**Issue by lfmundim** [J-D-K/JKSV#180]
Hey there, I'm trying to use the new `02.23.2023` version of JKSV and it's constantly crashing on my device.

I have the latest pre-release Atmosphere (1.5.0 for 16.0) and latest Hekate too if that matters, on a CFW-d V1 Switch.

Steps:
* Boot into CFW
* Open Photo Album to get into Homebrew
* Open JKSV

Error Code from Atmosphere: 2168-0002 (0x4a8)
Program: 010000000000100D

**Comment by lfmundim** [comment]
Some troubleshooting I did:
* Look for a folder with that name under `atmosphere/contents`, none found
* Redownload the `.nro` file and delete from MicroSD, and readd. Didn't work
* Ran Mac's Disk Utility First Aid on it, no errors found
* Checked if it was FAT32, it is

**Comment by lfmundim** [comment]
Update: I had configured Google Drive integration following the guide you had. Removing the configuration JSON makes it work. 

The JSON:
```json
{
    "installed": {
        "client_id": "[REDACTED].apps.googleusercontent.com",
        "project_id": "optimum-web-[REDACTED]",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "[REDACTED]",
        "redirect_uris": [
            "http://localhost"
        ]
    }
}
```

**Comment by J-D-K** [comment]
Your problem is that you're using the photo album to launch. It doesn't have enough ram to open the browser applet. Hold R while booting a game and it will work.

**Comment by lfmundim** [comment]
Nope! That's on my first comment as troubleshooting. Didn't work if I have Google drive configured

**Comment by J-D-K** [comment]
Oh, I missed that. I'm going to have to look at it some other time. I don't have my switch charged. I'll get back to you when I have time this weekend.

**Comment by lfmundim** [comment]
No rush! I saw that GD integration is still halfway done so I don't currently need it, but it's good to keep that on the radar

**Comment by rado0x54** [comment]
@lfmundim let me know if this was your issue: https://github.com/J-D-K/JKSV/issues/204#issuecomment-1621955008
