### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by impeeza** [J-D-K/JKSV#186]
Hi, thanks for all your great work.

Since last week every time I try to build from source JKSV I get an error, I was trying on Linux, Windows (MSYS MinGW) and WSL. and the error are the same:

![image](https://user-images.githubusercontent.com/41979604/230743092-d1612ab4-1c1e-4087-9d3e-85e9eaa06faa.png)

I don't know what changed on the homebrew switch packages but this is weird, @J-D-K do you know what could be?

thanks again.

**Comment by J-D-K** [comment]
It looks like libnx was updated and they changed the names of some things inside the play statistics struct. Not a hard fix at all. I don't really understand why it was necessary though...

**Comment by impeeza** [comment]
you and me, Libnx seems changing a lot on the last month, but well, thanks a lot for taking the time to look into my question.

regards from Colombia.

**Comment by impeeza** [comment]
Using your insights and considering that I am not a programmer, I just compare a past working **LibNX** commit with newer **Libnx** and found the variables and properties name changed, also found a struct which change his name, but a new struct with the original name was created.

On **LibNX** the file `pdm.h` define the new STRUCT `PdmPlayStatisticsV1` supposedly is auto translated to `PdmPlayStatistics` when is needed but on the JKSV's `data.h` file I did needed to change the `PdmPlayStatistics` on the row 40 to `PdmPlayStatisticsV1` in order to correct build, I really get confused about that.

I am creating a PR (https://github.com/J-D-K/JKSV/pull/187) with the changes I just made in order to get a correct build from latest LibNX

Please review it and correct as needed.

Hope the PR helps a little.

**Comment by impeeza** [comment]
Sadly after so many test and tries the build version with the PR 187 doesn't works on my Switch, nor firmware 15.0.1 nor 16.0.1 sorry.

**Comment by pixeltester** [comment]
What's the point of making a PR if you have no idea what you're doing..?

**Comment by J-D-K** [comment]
So I've looked at libnx today. It looks like firmware 16 made changes to the pdm play stats stuff and that's why it was updated and changed. I'll try to get to it Friday, but no promises. Changing that to the V1 isn't going to work. I'm assuming libnx takes care of that for you depending on what firmware it detects when you init. It's just a matter of changing the names to the new ones.

**Comment by impeeza** [comment]
Thank you so much, regards from Colombia

**Comment by J-D-K** [comment]
I'm going to need to spend more time on it later. It's building again, but with firmware 16+, they've changed from returning minutes played to nanoseconds played. The times are slightly off right now. Once I have time and am actually awake and can focus better, I'll get them more precise.

**Comment by impeeza** [comment]
Hello there, sorry for overseeing this Issue, Some time ago the issue was resolved, and I haven't closed nor thank you for the changes.  So here I am thanking you so late what I am embarrassed.

Regards.
