### ISSUE TITLE
Is there any chance that adding WebDAV support for JKSV ?

### ISSUE THREAD

**Issue by zzeking** [J-D-K/JKSV#188]
The GD space is limited, and I would like to host my own cloud server. And WebDAV is an easy_to_use file service. Thanks a lot.

**Comment by Rikj000** [comment]
This feature would be much appreciated!   
Imho, spyware, such as Google drive, should not be recommended to users.

**Comment by fennectech** [comment]
FTPD is already a thing.  Windows explorer supports it

**Comment by rado0x54** [comment]
Duplicate with #148 

Hey @J-D-K I've added a PR #207  for Webdav support. The PR puts the Webdav implementation and the Google Drive implementation behind a common interface. Would love to get this merged.

@zzeking @Rikj000 @fennectech  I'd love to have you test it. Thanks!
