### ISSUE TITLE
App freeze when new save backup is choose

### ISSUE THREAD

**Issue by linkcelula** [J-D-K/JKSV#190]
When I enter the app and push new save backup app freeze and I have to force turn off console.
I use 16.0.2 and last atmos.

**Comment by Arusene-Arsene** [comment]
yep me too

**Comment by impeeza** [comment]
please explain more, what are your versions?  for me on FW 16.0.2, Atmosphère 1.5.3 and JKSV 02/23/2023
09f610b  all is working fine, I can create saves and upload to GDrive.

**Comment by sprinklinz** [comment]
This is happening to me as well, but only when I try exporting a backup for Tears of the Kingdom. It crashes when exporting the progress.sav file, and the file ends up being 0kb.

**Comment by Arusene-Arsene** [comment]
> please explain more, what are your versions?  for me on FW 16.0.2, Atmosphère 1.5.3 and JKSV 02/23/2023
> 
> 09f610b  all is working fine, I can create saves and upload to GDrive.  
> 
> 
Well I'm using latest firm and ams

**Comment by them4ko** [comment]
The same thing is happening to me.

TOTK 1.1.0  -  JKSV 2/23/23 - Crash "Error Code: 2168-0002" when "progress.sav" is saved.

**Comment by them4ko** [comment]
SOLUTION / RESOLVED:

J-D-K answered in another post about something similiar:

"Your problem is that you're using the photo album to launch. It doesn't have enough ram to open the browser applet. Hold R while booting a game and it will work."

And indeed - starting through the "R" method - works !

**Comment by WispySkies02** [comment]
I am having the same issue of the switch freezing when selecting new backup, however, I am running title override mode

**Comment by J-D-K** [comment]
I've added an applet mode warning when you boot JKSV under the album so I'll consider this closed. I'm not sure if the rewrite will disallow it completely or not yet.
