### ISSUE TITLE
Google Drive issue won't launch with .json

### ISSUE THREAD

**Issue by DurriePuncherR** [J-D-K/JKSV#193]
I've gone through the setup to build my own and put the .json in SD:/config/JKSV/ but now when launching I get "The software closed because an error occurred.", I looked at the log file in /JKSV/ but that's empty

**Comment by zaggash** [comment]
https://github.com/J-D-K/JKSV/issues/185#issuecomment-1551545243

**Comment by DurriePuncherR** [comment]
> #185 (comment)

Thanks for your reply, I do that most of the time though

**Comment by zaggash** [comment]
> > #185 (comment)
> 
> Thanks for your reply, I do that most of the time though

Could you close the issue if it solved ? ;)

**Comment by DurriePuncherR** [comment]
> > > #185 (comment)
> > 
> > 
> > Thanks for your reply, I do that most of the time though
> 
> Could you close the issue if it solved ? ;)

Hi, the issue is still the same

**Comment by rado0x54** [comment]
@DurriePuncherR Check out https://github.com/J-D-K/JKSV/issues/204#issuecomment-1621955008

**Comment by rnblanco** [comment]
@rado0x54 Could you please show me how to run this build?

**Comment by J-D-K** [comment]
Rewrite is going to use a hard coded path with fixed name in the future. I found out that Google actually changes the file name depending on what country you're from...
