### ISSUE TITLE
Google drive error

### ISSUE THREAD

**Issue by masterblaster221** [J-D-K/JKSV#195]
Failed to start drive it says when I connect to drive with my gmail

**Comment by philippthiele** [comment]
Same for me, log.txt file in JKSV folder says:
> Drive/exchangeAuthCode: CURL returned error 60

**Comment by pog221** [comment]
I had to go into the Switch system settings and sync clock via internet to fix this.

**Comment by rnblanco** [comment]
I am sorry, which was the resolution? I tried sync clock via internet but the error is still there. PS: I did not build the project myself, it is confusing.
