### ISSUE TITLE
ID titles

### ISSUE THREAD

**Issue by Lowitle** [J-D-K/JKSV#196]
Hello,

The system saves don't show images, it shows numbers like it were ID's.

00000080
00000152
00001020
00001061
00001071
00001091
000010B0
000010C0

How can I know which one is the game I want to back up the safe?

**Comment by impeeza** [comment]
Reading the documentation and text on your screen.

you are looking on SYSTEM saves, if you don't know what they are, probably you will not need it.

This space is for Issues and Bugs report, if you need support, please go to Discord or GBATemp.
