### ISSUE TITLE
JKSV no workie

### ISSUE THREAD

**Issue by jahga** [J-D-K/JKSV#197]
When I downloaded jksv.nro to my desktop it went smooth. However, I tried to copy it to my "switch" folder in my sd card and its gets stuck everytime around 80%, wont go further, then HB gives me a error message within the USB tool. Ive tried several times to no avail, any suggestions?

**Comment by impeeza** [comment]
may be your card is fake or damaged, put on your computer and use h2testw for testing it.

please for support go to gbatemp or discord, this is a issue and bug report space.
