### ISSUE TITLE
Google Drive Connected: Upload all?

### ISSUE THREAD

**Issue by nwg5817** [J-D-K/JKSV#198]
Sorry in advance, I know there are a million G-Drive issues posted. 

Is there a way to upload all dumped save files or do you have to upload each manually?

**Comment by J-D-K** [comment]
It's coming with auto-upload. I still don't have a ton of time, but I sneak in a bit here and there when I can.

**Comment by zaggash** [comment]
> 

Thanks for that, you're awesome

**Comment by nwg5817** [comment]
Great to hear, thanks jdk.
