### ISSUE TITLE
Exporting Minecraft (Bedrock Edition) save file freezes halfway through

### ISSUE THREAD

**Issue by FutabaHoneyOTU** [J-D-K/JKSV#2]
It will freeze when exporting MCBE save file on a .mcpack file

**Comment by J-D-K** [comment]
Does it freeze with a black bar, or does it start the file and then freeze?

**Comment by J-D-K** [comment]
@98otiss03 Is this still an issue or what?

**Comment by fennectech** [comment]
@98otiss03

**Comment by 98otiss03** [comment]
It will freeze halfway through transferring that file.

**Comment by J-D-K** [comment]
Hmm. Ok. I'll drop a build when I have time that displays some extra info if you're up for it. The only other time I've experienced something like this was a system save archive, but that failed completely and couldn't even get the file size.
