### ISSUE TITLE
Save data creation failed(402) and animal crossing dont show up in the menu create savedata

### ISSUE THREAD

**Issue by hanswurst31** [J-D-K/JKSV#200]
old titel: Is it possible to import savegames/profile which are exported via NXnandmanager

My Switch(nandbackup) is bricked. i revived this console with a donor nand. its working now but all data are gone and Serial number is XAW0000..... i can still open the old nandbackup and can see the savegames/profiles and can export the user partition. Can i use this with nxnandmanager exported data with JKSV? if yes, how do i do it? THX

**Comment by impeeza** [comment]
Hello there the is a great tutorial about extract savegames using NXNandmanager then you can use them on JKSV to restore them.

This is a space for issues or bug report. For support you are welcome on GBATemp or discord

https://gbatemp.net/threads/recovering-games-saves-from-nand-using-nxnandmanager-and-jksv.620758/

**Comment by hanswurst31** [comment]
ok thx. just following the tutorial and im facing some errors? im trying to create save data and it works for most of the games but for some it doesnt with an error: failed to create savedata. and for some games like animal crossing doesnt show up. i can run the games perfektly. any idea what im doing wrong?

**Comment by J-D-K** [comment]
That error is related to creating the filesystem on NAND and it means it already exists. I need to think of a clearer way to differentiate between that and creating backups. I'll make a note of it.
