### ISSUE TITLE
Goggle Drive Integration

### ISSUE THREAD

**Issue by brown3m7** [J-D-K/JKSV#204]
Im unable to get Google drive integration to work. I have followed the steps and created two separate .JSON files and each time it will give me "the software was closed because of an error occurred" and when trying to open in Applet mode it says "Error code 2168-0002 (0x4a8)". Im on 16.0.3

Ive downloaded the most recent JKSV and it shows it being the 2.23.2023 version. Im not sure what im doing wrong.

**Comment by J-D-K** [comment]
How are you launching JKSV? If you're using the album, it doesn't have enough RAM to open the browser applet. You need to use a game if you want drive support.

**Comment by brown3m7** [comment]
Hello I launched it both ways. The first way which was holding down R got me the error  "the software was closed because of an error occurred" while opening it applet mode crashes the whole system with the error "Error code 2168-0002 (0x4a8)".

**Comment by rado0x54** [comment]
Hey, I ran into this issue. JKSV crashes if there ALSO exists a `._client_secret` in the directory that is created by Mac OS.

![Screenshot 2023-07-05 at 11 04 29](https://github.com/J-D-K/JKSV/assets/1713643/2e50fdc8-dc21-4be9-a72b-10f825f825b1)

**Comment by brown3m7** [comment]
Hello! Yes I did create the .JSON file using Mac OS. If I create the file using a PC would that resolve the issue? Can I still use MAC OS to load the file?

**Comment by rado0x54** [comment]
You can create the file whereever you want. Just make sure in the final directory there is ONLY ONE file that contains "client_secret". :)

**Comment by brown3m7** [comment]
It worked! Thanks so much!

**Comment by rnblanco** [comment]
Hello everyone, I am having the same issue and getting this error on the log:

`
Drive/exchangeAuthCode: {
  "error": "invalid_request",
  "error_description": "Missing required parameter: code"
}
`

Despite having the file in config/JKSV/client_secret.json
