### ISSUE TITLE
エラーによってソフトが終了される

### ISSUE THREAD

**Issue by nibenn** [J-D-K/JKSV#208]
Rボタンの置換機能によって起動しているもののソフトウェアが強制終了されてしまいます。
新しく導入しても解決せず困っています。

**Comment by impeeza** [comment]
I do recommend to look for help on discord or GBATemp, and using english.

regards.

**Comment by J-D-K** [comment]
I tried translating this and unfortunately I can't make out what you're talking about. I'm really sorry. I only speak English with some random Pennsylvania German swear words I know because of my great grandmother. I wish I could help you. Sorry.
