### ISSUE TITLE
JKSV turs my save backups into empty, extension-less files

### ISSUE THREAD

**Issue by DinnerBug** [J-D-K/JKSV#209]
I recently had to reset my custom firmware and rebuild the partition based emuMMC. Backed up everything with JKSV before resetting. 

Now when i try to restore the saves, it doesn't do anything. I noticed that after transferring the save files and opening JKSV, the save folders got turned into extension-less files that are 0b big and with the same name as the folder or file they replaced.

This "transformation" only happens to files created before the reset. If I make a backup with this installation of JKSV it behaves normally.

**Comment by impeeza** [comment]
may be a corrupted SD Card?  use the post https://gbatemp.net/posts/9885418/ as guide to test your card.

**Comment by DinnerBug** [comment]
> may be a corrupted SD Card?  use the post https://gbatemp.net/posts/9885418/ as guide to test your card.

I apologize but for some reason I can't see the page that the first link in the comment leads to.
I formatted my sd card to fat32 utilizing Hekate's built in tool so I did that and carried on with H2testw. If H2testw returns a bad result does it mean the sd card is bad and needs to be replaced?

**Comment by impeeza** [comment]
Exactly that does means.

Don't worry is exactly that what the pussy on GBATemp says.

**Comment by DinnerBug** [comment]
The test I ran on the micro SD card returned with no errors

**Comment by DinnerBug** [comment]
It appears my NAND had gotten corrupted. This would explain why remaking just the emuMMC would not fix the issue. A NAND restore fixed the issue.
