### ISSUE TITLE
Allow SWKBD for Renaming in Applet Mode 

### ISSUE THREAD

**Issue by SassyCultist** [J-D-K/JKSV#21]
By default, Atmosphere uses it's system settings ini file to reserve enough memory for the SWKBD when running homebrew in applet mode. I updated from JKSV's 3.21.20 release to the 4.10.20 prerelease and noticed that I was no longer able to name backups in applet mode so it would be nice to have this feature back.

**Comment by J-D-K** [comment]
Ok. I know it works on atmo. Got annoying telling people to hold L or R on SX though.

**Comment by SassyCultist** [comment]
If telling people to hold L or R on SX is undesirable, then I think it is possible to detect if a person is running SX like the homebrew Edizon does. 
Relevant code in Edizon: 
https://github.com/WerWolv/EdiZon/blob/master/source/helpers/util.c#L31
https://github.com/WerWolv/EdiZon/blob/master/source/main.cpp#L198

**Comment by J-D-K** [comment]
I'm probably just going to remove the applet mode detection now that the animal crossing stuff is dying down a little.

**Comment by J-D-K** [comment]
Here. Let me know if you have any problems with it. I was changing some things here and there. I always give it a quick rundown, but you never know.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/4536578/JKSV.zip)
