### ISSUE TITLE
[Feature Request] Payload Possibility?

### ISSUE THREAD

**Issue by LokeYourC3PH** [J-D-K/JKSV#215]
I was curious if turning this into a payload for RCM would be possible, as it would basically allow transfer between OFW & CFW saves easily without a lot of hassle. It would also allow manual backup of OFW saves without needing to dirty your SysNAND.

**Comment by fennectech** [comment]
This would be a ground up redesign    This application relies entirely on both libnx and horizon.  Neither of which are available from a payload.       Access to an offline sysnand is much more likely

**Comment by LokeYourC3PH** [comment]
> This would be a ground up redesign This application relies entirely on both libnx and horizon. Neither of which are available from a payload. Access to an offline sysnand is much more likely

A very simplified version would be enough I suppose.
