### ISSUE TITLE
Could you please tell me how to run the project correctly?

### ISSUE THREAD

**Issue by rnblanco** [J-D-K/JKSV#216]
I am a software developer, but have no idea how C++ works. I am having an error obtaining the credentials for GD from the .json file and I would like to fix it myself, due to we all know you are very busy rigth now.

Could you please tell me how to run the project correctly? I am having trouble compiling my own versions :(

**Comment by J-D-K** [comment]
I'll try to write some better building instructions in the readme next time. I'd help, but that's not what git issues are for.
