### ISSUE TITLE
Set JKSV save folder location

### ISSUE THREAD

**Issue by Corgano** [J-D-K/JKSV#22]
Looking for a way to change where JKSV saves files. Right now it saves them to <root>/JKSV, but I HATE having my root cluttered with a bunch of crap. Other tools like Checkpoint and NXdumptool use <root>/switch/Checkpoint or NXdumptool directory (or <.nro folder directory>) to save their crap in, and I'm looking to do the same

Any way i can set JKSV to save to <root>/switch/JKSV instead?

**Comment by Corgano** [comment]
/src/file.cpp, line 135
        mkdir("sdmc:/JKSV", 777);
        logOpen();
        wd = "sdmc:/JKSV/";
to
        mkdir("sdmc:/switch/JKSV", 777);
        logOpen();
        wd = "sdmc:/switch/JKSV/";
If I had any idea how to compile it I'd just do it, but I am a noob at cpp and have no idea what I'm doing.

**Comment by J-D-K** [comment]
I'll work something out to make sure it's backwards compatible with the current setup. JKSV has used that folder since 2016 on 3DS.

**Comment by Corgano** [comment]
Ahh fair enough. I'm just trying to tidy up, there are a lot of things that drop files in root :/

**Comment by J-D-K** [comment]
Create a file named `jksv_dir.txt` in your switch folder and type `sdmc:/switch/JKSV/`, or whatever you want to use in it. It will create the path if needed. It's the best I can think of since it can't use the root JKSV folder to search. It defeats the purpose.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/4562061/JKSV.zip)

**Comment by Corgano** [comment]
That works, awesome.

**Comment by Corgano** [comment]
Just out of curiosity, would it be possible to make the jksv_dir.txt ALSO be in sdroot:/switch/JKSV? It's fine if that's not possible

**Comment by J-D-K** [comment]
It actually can't. The path is set using that, so, without it JKSV would have no idea to use that directory to find it. It also creates a problem where if someone uses a different folder than switch/JKSV, they'll have an extra folder for nothing more than a text file. It really doesn't matter what you put in it. You could point its path to checkpoint or edizon's paths and I would just accept and use them.

**Comment by Corgano** [comment]
Ahh right that makes sense
