### ISSUE TITLE
How to transfer saves between users? 

### ISSUE THREAD

**Issue by AlexandreDecan** [J-D-K/JKSV#221]
Hello,

First of all, thank you for this really nice tool! I'm really new to Switch and to Homebrew, so apologize if my question doesn't make sense or if it was already answered in the past (I searched for it, but couldn't find!). When I received the Switch, I created an account for each of my children. Then we realise that some of the games are meant to be played in a kind of "shared account" (e.g. Smash bros, Minecraft Dungeons, etc.). So my goal is to create such a "Shared account" and to move existing saves from some combinations of users/games to this account. That way, we'll use the "shared account" to store our common progresses in several games. 

What I tried so far: 
 - I opened JKSV and went to one of my children's account; 
 - I selected the games for which I wanted to move the saves, and "save the saves"; 
 - I selected the "shared account"; 
 - I created what I guess are "empty savegames" for this account/these games (second option in the list IIRC); 
 - I "restore"-d the saves from point (2)

However, when I launch the games using the shared account, it seems they start from scratch. Did I miss something? 

Thanks in advance for your help!! :-)

**Comment by Pedsub984** [comment]
https://www.youtube.com/watch?v=HoyvuH2GU0Q&t=11s

This video might be helpful

**Comment by AlexandreDecan** [comment]
Thanks!
