### ISSUE TITLE
WebDav doesn't work or provide any logging

### ISSUE THREAD

**Issue by thejra** [J-D-K/JKSV#226]
I've setup a WebDav share and confirmed working (Read/Write).

I followed the instructions here: https://github.com/J-D-K/JKSV/blob/master/REMOTE_INSTRUCTIONS.MD

It says....

> The next time you start JKSV on your Switch, you should get a popup about the Webdav status
> If problems arise, check the log at SD:/JKSV/log.txt

I can confirm that:

1. I don't get a "popup about the Webdav status"
2. The SD:/JKSV/log.txt file is empty (0 bytes).
3. I've verified the json file is named correctly, holds valid JSON and has the correct variables.

**Comment by rado0x54** [comment]
Did you build JKSV yourself? The latest release does not contain the WebDav code yet.

**Comment by weakvar** [comment]
> > Did you build JKSV yourself? The latest release does not contain the WebDav code yet.
> 
> That's weird, I wonder why that is

Ah.. I see! There's [your fork](https://github.com/rado0x54/JKSV) with WebDav implementation. Will try your release instead of the last one here

**Comment by HenryBaby** [comment]
Just an fyi, the official release now supports WebDav.

**Comment by thejra** [comment]
> Just an fyi, the official release now supports WebDav.

Thank you!!

**Comment by thejra** [comment]
> Just an fyi, the official release now supports WebDav.

Annoyingly I want to use Synology NAS for Webdav and one of the comments says it won't work (yet, until they improve WebDav compatibility in JKSV) :(

**Comment by rado0x54** [comment]
@thejra this issue should be closed.
