### ISSUE TITLE
WebDAV save files are not displayed properly

### ISSUE THREAD

**Issue by 320x200** [J-D-K/JKSV#227]
Hello,

There is something wrong going on when remote save files are listed. The filenames are not displayed only their `[R]` prefix.

**Comment by impeeza** [comment]
On WebDav is a know issue, had to do with the server, in my case Apache, using IIS do not have the issue.

https://github.com/J-D-K/JKSV/pull/207

So far J-D-K is making some updates to the code and the WevDav support will be taken on account once the new code is done:  https://github.com/J-D-K/JKSV/pull/207#issuecomment-1934701585

**Comment by 320x200** [comment]
Oh I see! I did not think too look into the PR to see if this was discussed already. Thanks for the info!

**Comment by rado0x54** [comment]
Happy to take a look at that issue. (Also see: https://redmine.lighttpd.net/boards/2/topics/11473 as mentioned in #207)
