### ISSUE TITLE
Google Drive: Unable to log in - Error Code: 2800-1810 The certificate has either expired or is not yet valid.

### ISSUE THREAD

**Issue by Pedsub984** [J-D-K/JKSV#229]
Hi, I'm not being able to log in to Google Drive and getting the following error:

_Error Code: 2800-1810 
The page cannot be displayed because the security of the page's certificate cannot be confirmed.
The certificate has either expired or is not yet valid. Please make sure the console's date and time settings are correct.
Issue Date: 16/04/2024 05:20:36
Expiration date: 09/07/2024 05:20:35_

Updated FW to 18.0.1, JKSV is 2.23.2023, Atmosphere is 1.7.0. 
Loading JKSV in non-applet mode. 
Date and time are set correctly (manually).
I'm pretty confident I've followed the instructions on REMOTE_INSTRUCTIONS.MD correctly.

Has anyone come across this issue? Any solution to make the certificate work?

**Comment by rollinfonzy** [comment]
same issue with my 18.0.1 switch but it works on my other 19.0.0
Amy solution?

**Comment by impeeza** [comment]
look for the consoles RTC real time clock and for DNS MiTM

**Comment by J-D-K** [comment]
I don't want to be a jerk, but this has something to do with your system's clock as far as I know. JKSV has no control over this so I'm going to close this. Try searching for tools that can correct this or help somewhere else.

**Comment by SezBulent** [comment]
I understand it's closed, but what is exactly the solution?
Though my issue is a little different, I have two different cfw switch devices running atmosphere, same region, same time zone, both synced with ntp, in system and hekate, yet i started getting "the page can not be displayed" consistently.

**Comment by impeeza** [comment]
> I understand it's closed, but what is exactly the solution? Though my issue is a little different, I have two different cfw switch devices running atmosphere, same region, same time zone, both synced with ntp, in system and hekate, yet i started getting "the page can not be displayed" consistently.

The answer is exactly above your message, the console had the incorrect clock setting so the certificates are invalid.

**Comment by SezBulent** [comment]
> The answer is exactly above your message, the console had the incorrect clock setting so the certificates are invalid.

@Pedsub984 has never confirmed this was the problem, he even stated that the times are properly set. Probably for my problem I might need to open a new issue, but why would I be getting this error? The browser works correctly and I can access any website.
