### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by simonarhaegar** [J-D-K/JKSV#231]
Does this version work with 13.2.1 and AMS 1.2.6/S and if not, could someone tell me which version should I use instead?

**Comment by impeeza** [comment]
yes without problem, please download the latest one from https://github.com/J-D-K/JKSV/releases and close the issue.

**Comment by impeeza** [comment]
even this is a build of latest commit on main branch

[2024_02_06-df89d8b-PR207incluido-ESV3.zip](https://github.com/user-attachments/files/16229225/2024_02_06-df89d8b-PR207incluido-ESV3.zip)

**Comment by simonarhaegar** [comment]
thanks!
