### ISSUE TITLE
A question about the characters used in WebDAV cloud storage paths.

### ISSUE THREAD

**Issue by LUYANJIA6036** [J-D-K/JKSV#238]
When using a WebDAV service provider that does not support colon characters in file paths to store game files of "The Legend of Zelda: Breath of the Wild" and "The Legend of Zelda: Tears of the Kingdom,"  I encountered a problem where the folder could not be created on the WebDAV server during the game, causing the game save to fail. 
To avoid this issue,  I tried using the "Change Output Folder" feature;  it worked locally with the new folder named "Breath of the Wild," but the change was not successfully applied to the folder on the WebDAV cloud. So it still the original path and webDAV still can’t be used。

**WebDav service provider**: https://dav.jianguoyun.com/dav. a China service provider. 
**log:** "WebDav: Create directory at https://dav.jianguoyun.com/dav/nsbackup/JKSV/The%20Legend%20of%20Zelda%3A%20Breath%20of%20the%20Wild/"
**Service provider's response**：the nustore path is not valid /The Legend of Zelda: Breath of the Wild

**Comment by LUYANJIA6036** [comment]
I looked at some code,  but I'm not good at C language, so I can't modify it

**Comment by impeeza** [comment]
have you even look on closed issues?, this is duplicated with:

https://github.com/J-D-K/JKSV/issues/235

latest binary can be downloaded from:

https://gbatemp.net/download/jksv-2024_07_27-df89d8b-pr236-oficial-esp3.38737/

Please close this issue.
