### ISSUE TITLE
WEBDAV basepath setting must be in URI format

### ISSUE THREAD

**Issue by nimaskji** [J-D-K/JKSV#239]
Hi there :-)

Thanks a lot for your soft, I m been waiting for this feature long time ago !

Just to inform you tha tthe setting basepath in webdav.json file must be in URI format.

Step to reproduce :
```json
{
  "origin": "https://dav.something.fr",
  "basepath": "Games Saves",
  "username": "Administrateur",
  "password": "MyStrongPassword"
}
```

Step to fix it in the actual version (07.18.2024):
```json
{
  "origin": "https://dav.something.fr",
  "basepath": "Games%20Saves",
  "username": "Administrateur",
  "password": "MyStrongPassword"
}
```
Hope this is help some guys just like me who want ot use webdav feature :-)

**Comment by impeeza** [comment]
Thank you so much.  I will make a PR about this on the instructions MD.

**Comment by J-D-K** [comment]
If there are no problems now I'm going to close this.
