### ISSUE TITLE
Cant switch the User.

### ISSUE THREAD

**Issue by StiefelHD** [J-D-K/JKSV#24]
Hello, i will try to save the saves from Animal Crossing.

My first account work, but the i cant switch to the second user.
i try L or R but i change only the folder (from Device to BCAD as simple)..

Any helps?

**Comment by J-D-K** [comment]
A user account needs save data in order for JKSV to see it. Device saves are attached after everything is loaded, so even with the option enabled, they don't count towards that currently.
