### ISSUE TITLE
[Feature request] Merge local and remote list items and add auto-upload of new saves

### ISSUE THREAD

**Issue by Romnet** [J-D-K/JKSV#242]
Hello. Thank you for your great software. I was also glad to see the ability to upload saves to WebDAV. I have a couple of suggestions on how to make it even more convenient.

1. Currently, remote and local saves are displayed on separate lines. Therefore, it is not obvious which saves have been uploaded and which have not yet. To upload a save to the server, you need to find the desired line by name. I suggest displaying saves with the same name on one line, but marking local files, for example, with an additional letter L.
2. At present, it is possible to create backups for all games, but there is no way to automatically upload them to a remote server. I suggest adding an option to the settings, after activating which and if there is a configured connection, saves are uploaded automatically when they are created.

**Comment by J-D-K** [comment]
I'm doing what I can when I can. Auto upload is going to be added with the rewrite. The current master branch is a nightmare to navigate.

**Comment by Romnet** [comment]
Thank you for your reply and your work. I understand that this is all done on enthusiasm in your free time. I'm glad to know that auto upload is in the plans.
