### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by fzziii** [J-D-K/JKSV#252]
Why does the following pop-up appear after upgrading from version 02.23.2023 to 11/05/2024, and there is also an APPLET MODE in the upper left corner (which was not present in previous versions)

![2024110920290100](https://github.com/user-attachments/assets/18395e8f-c1e3-4efd-a487-03ae084e86af)

**Comment by J-D-K** [comment]
Because you're running it under the album? There's supposed to be a warning about certain things not working, but since no one was available to update the translation at the time, it's blank. I don't use the album to launch it so I didn't think to check that.

**Comment by impeeza** [comment]
> Why does the following pop-up appear after upgrading from version 02.23.2023 to 11/05/2024, and there is also an APPLET MODE in the upper left corner (which was not present in previous versions)
> 
> ![2024110920290100](https://private-user-images.githubusercontent.com/39999647/384604478-18395e8f-c1e3-4efd-a487-03ae084e86af.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUyMTcsIm5iZiI6MTczMTE2NDkxNywicGF0aCI6Ii8zOTk5OTY0Ny8zODQ2MDQ0NzgtMTgzOTVlOGYtYzFlMy00ZWZkLWE0ODctMDNhZTA4NGU4NmFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDE1MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYTlhYjU2NWM1NzIxZTJkNTAzY2NmNDM1MDE4OTFhNTg1ZmJlNzcxNDVmNGI4MGVjZTNiZTg4YjA0M2VlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.to_KLaYvpWQEyYRjwSP5pmj7eWH4UlSMyNsELDNoS0I)

You are running the JKSV trough the album applet,  please load you HBL pressing AND DO NOT RELEASING the [R] button while loading any title.  Then from there launch JKSV

**Comment by fzziii** [comment]
@J-D-K @impeeza  Thank you for your reply!   After changing the language to English, I saw the following warning message. But what I'm curious about is that the 20230223 version doesn't have such a warning message. If I'm running the JKSV(2024/11/05) trough the album applet,will there be any functional impact? 
![1](https://github.com/user-attachments/assets/735a8f18-a59f-495b-a8e8-2e187fc8a48e)
![2](https://github.com/user-attachments/assets/2ff71ddc-9a9d-4e38-a71a-d918e29ed555)

**Comment by impeeza** [comment]
The Warning was added after so many issues with Applet mode, is advised on the README to not use the applet mode but is ignored for so many users, so the latest commit the warning was introduced.

**Comment by fzziii** [comment]
Okay, I know how to use it correctly now. Thank you very much~

**Comment by impeeza** [comment]
Please close the issue :D
