### ISSUE TITLE
One click backup of all game saves

### ISSUE THREAD

**Issue by fzziii** [J-D-K/JKSV#253]
A small suggestion, when using the webdav feature, I hope to be able to create game save backups for all games with just one click and support one click upload. I have lost my game save due to a damaged SD card. I am well aware of the importance of saving to players, and I hope to have such a quick function to protect all game saves. Thank you~

**Comment by impeeza** [comment]
There is a duplicated issue about this,  on the settings there is a non working item «Auto Upload» that will be reviewed on the next rewrite of the code.

https://github.com/J-D-K/JKSV/issues/242#issuecomment-2308393177

https://github.com/J-D-K/JKSV/issues/243
