### ISSUE TITLE
Can't exit file mode

### ISSUE THREAD

**Issue by viktorashi** [J-D-K/JKSV#258]
I can't figure out how, and not even the project's docs don't state how to go back once you've entered file mode, other than '+' to close JKSV all-togather or something

**Comment by J-D-K** [comment]
IIRC, you press minus again. That should do it.

**Comment by viktorashi** [comment]
> IIRC, you press minus again. That should do it.

yep, hellyeah thanks a ton for respondong so quick too, YOU'RE THE GOATT KEEP DOING YOUR SHIT BRO

**Comment by viktorashi** [comment]
> IIRC, you press minus again. That should do it.

yep, hellyeah thanks a ton for respondong so quick too, YOU'RE THE GOATT KEEP DOING YOUR SHIT BRO
