### ISSUE TITLE
Animal Crossing Save Data Restoring Issue

### ISSUE THREAD

**Issue by bababeeba** [J-D-K/JKSV#26]
Hello all, so I edited my animal crossing save and am able to play the game with my edited save that I restored to my system with JKSV when I launch my switch in "homebrew mode", if you will. However, when I power on the switch normally ie without entering RCM or anything, the save data is the non-edited version. Am I missing something? Why can I play the game on my edited save in "homebrew mode" but not in "standard mode"? Any sort of help is appreciated, thank you!

**Comment by bababeeba** [comment]
If it helps, I used switch.homebrew.guide as an exact guide. Does it have something to do with homebrew running off of my SD card and "standard mode" running off of the system itself? Should I move the normal game data from my system to the SD card? Is that safe to do with homebrew files already loaded onto that card?

**Comment by J-D-K** [comment]
If you want to transfer your save to the "legit" version, you need to run JKSV on your sysnand. Turn on airplane mode and restore it. There is always some risk when running homebrew on sysnand though.
