### ISSUE TITLE
No folder named ''Switch'' 

### ISSUE THREAD

**Issue by Toff01** [J-D-K/JKSV#260]
When I connect my mirco SD into the convertor in my laptop, I am only greeted with 1 filed names ''Nintendo''. The contents inside this include another 3 files named ''Albums'' ''Contents'' and ''Saves''. However on all the tutorials ive watched everybody has a folder named ''Switch''. What is my reason for not having this and what do I need to do in order to have it?

**Comment by impeeza** [comment]
That is not a JKSV issue, and this is not a support site.

may be your console is not modded.

please go to discord or https://gbatemp.net/threads/switch-noob-paradise-ask-questions-here.488277/  and ask for support, please be more specific including al relevant data such console type, injection method, FW version Atmosphère version etc.
