### ISSUE TITLE
Having trouble using this with ACNH

### ISSUE THREAD

**Issue by mitch-zink** [J-D-K/JKSV#27]
I'm using JKSV & NHSE to modify a save. No matter what I do, I can't get any save to "restore". Every time I try and boot up the game it starts as a new game/save instead of my backup or modified one. I tried a lot of different troubleshooting steps, but I can't get it to work. Any help would be very much appreciated. Thank you.

**Comment by J-D-K** [comment]
Does the original, non-edited version restore and work?

**Comment by mitch-zink** [comment]
Unfortunately not, no

**Comment by mitch-zink** [comment]
I couldn't get a new save to restore either

**Comment by J-D-K** [comment]
Hey, sorry I disappeared for a little while. Did you get anywhere, or are you still having issues?

**Comment by mitch-zink** [comment]
Hey man, could you possibly do me a favor and delete this? I use my github for job seeking purposes and I noticed it wouldn't let me delete it on my end. Thanks!
