### ISSUE TITLE
Add a feature in the options menu to remove the "overwrite to hold" feature

### ISSUE THREAD

**Issue by Elionna** [J-D-K/JKSV#28]
It slows down my use case as I always overwrite a certain save slot, an option menu to disable that protection feature would be nice

**Comment by J-D-K** [comment]
I already added this a little while ago. I'll get back to ya with a newer build when I can.

**Comment by 424778940z** [comment]
Same issue here, I'm doing save analyze which read and overwrite a lot, this is really annoying.
Please give an option to turn it OFF....

**Comment by J-D-K** [comment]
@424778940z It's already in the source. You're more than free to build it yourself if you need it asap.

**Comment by Elionna** [comment]
No rush, thank you for adding it, I'll pick it up when you put out a new release

**Comment by J-D-K** [comment]
@Elionna Oh, no. Don't worry about it. I just meant that if it was that important to them, they could build it themselves. I was busy and didn't have time to build it that very moment. So, here. Just remember, Erase means it's gone from your system, not SD/Folders. 
[JKSV_05.14.2020.zip](https://github.com/J-D-K/JKSV/files/4631517/JKSV_05.14.2020.zip)
