### ISSUE TITLE
About en-US.txt

### ISSUE THREAD

**Issue by qazrfv1234** [J-D-K/JKSV#30]
Localization is amazing!
If possible, I need whole strings to try full localization.
Thanks for your time.

![0520](https://user-images.githubusercontent.com/30403706/82580090-48c3b400-9bc1-11ea-9e78-b242d4dcbdcc.jpg)

**Comment by J-D-K** [comment]
I still need to figure a few things out first. I've been hesitant to do this before and on 3ds because of keeping them up to date.

**Comment by qazrfv1234** [comment]
Hi,
I completed the lastest file(\Roms\lang\zh-TW.txt)
May I send it to your mailbox for next update?thanks

**Comment by J-D-K** [comment]
Still got a tiny bit more to go. I appreciate it though. It's really cool!

**Comment by J-D-K** [comment]
I finally got a majority of the text translatable and fixed up the reading to make sure nothing is lost in loading. You can either pull-request your translation or send it to jksvswitch@gmail.com. I'd actually be interested in being able to use it to make sure there aren't any bugs as well as including it when I get around to a real new release.

Thanks!

**Comment by x43x61x69** [comment]
Is there a way to override the language option to force English? I got that it's nice to have native language support, but for some it's kinda confusing as the translation can't always be 100% accurate to everyone's understanding.

**Comment by fennectech** [comment]
The files are here so you can edit them.   If you want to improve the translation that's exactly what these files are for!

**Comment by J-D-K** [comment]
@x43x61x69 Done. Added a bool for it. Next git update will have it.

**Comment by J-D-K** [comment]
@x43x61x69 
Sorry it took a bit longer than I expected. I'm juggling keeping the current build running while redesigning the UI. I've added the bool to the bottom of the options list. Make sure to change it, press plus, and reopen. It should take care of it.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/6652456/JKSV.zip)
