### ISSUE TITLE
Option for auto naming

### ISSUE THREAD

**Issue by brlala** [J-D-K/JKSV#31]
Is there any option to disable auto naming like from the previous version when you click "New"?

I tried clicking "Ok" without typing anything but it just returns me to the Game Menu

**Comment by J-D-K** [comment]
You can hold L or R while selecting new to have it autoname the backup, if that's what you mean.

**Comment by brlala** [comment]
Thank you! That's exactly what I meant. Couldn't make up what does "Auto" means initially as nothing happened after clicking just the buttons by itself.
