### ISSUE TITLE
Crash when you erase the second game save data!

### ISSUE THREAD

**Issue by JamePeng** [J-D-K/JKSV#35]
![JKSV_crash](https://user-images.githubusercontent.com/17095606/83284622-7e931900-a20f-11ea-94a8-57a4056ca0a7.jpg)

**Comment by J-D-K** [comment]
Is this with your translation file? There was a similar issue with the traditional Chinese one.

**Comment by J-D-K** [comment]
Do you mean this screen? I've copied your file to my SD to check and I'm not having any crashes on either erase option. 
![2020052914392800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/39171744/83293934-7b217280-a1ba-11ea-9648-cb145a6caa00.jpg)

**Comment by JamePeng** [comment]
OK:) , I saw this message, but I try to create some photo to describe this problem
Enter the Nintendo user
![2020053009165600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17095606/83315945-c50b6680-a255-11ea-8cb3-b5529cb56feb.jpg)
Find any game in this interface and use the ZR erase function, eg.My Naroto save data. 
![2020053009175200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17095606/83316037-43680880-a256-11ea-9ac3-d25a2ee72908.jpg)
First time , it work, but the  focus point locate in the SD GUNDAM
![2020053009171700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17095606/83316104-a9549000-a256-11ea-92d2-7b107969234d.jpg)
But when I click the Button A, JKSV enter the AI game, the first game in the gamelist
![2020053009172100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17095606/83316279-84ace800-a257-11ea-8471-b445740038ad.jpg)
I try to use the ZR earse function again[ Second time ]
![2020053009145900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17095606/83316416-26ccd000-a258-11ea-872e-c3954b63110d.jpg)
press the Button A to finish the operation and then, it crash

**Comment by J-D-K** [comment]
Oh, ok. I actually probably know what's causing it. When you press B to go back to the title selection, it's supposed to unmount the save, but I don't think it is.

**Comment by JamePeng** [comment]
Even I didnt enter the game folder, when i did the second erase in this interface , it still crash again :(

**Comment by J-D-K** [comment]
Run this please and try to cause the crash. Afterwards, there will be a file inside your JKSV folder named log.txt. If it's not empty, copy it here. It should tell me where it's crashing.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/4704938/JKSV.zip)

**Comment by JamePeng** [comment]
ok

**Comment by JamePeng** [comment]
![jksv](https://user-images.githubusercontent.com/17095606/83317787-ea05d680-a261-11ea-89d9-4c4d51d9cc4c.png)
J-D-K， I tested your new version, this time it crashed by the third time erase operation, but i didnt see any error log in file.

atmosphere crash file:
[01590806651_010000000000100d.log](https://github.com/J-D-K/JKSV/files/4704991/01590806651_010000000000100d.log)


[01590806651_010000000000100d_thread_info.zip](https://github.com/J-D-K/JKSV/files/4704992/01590806651_010000000000100d_thread_info.zip)

**Comment by J-D-K** [comment]
OK. Thanks. After it deleted Caligula Overdose, it crashed, so it's somewhere in reloading titles. I'll get back to you. It's getting late here.

**Comment by J-D-K** [comment]
Ok, I can actually cause the same crash by using the rescan option over and over. I'll work on it over the weekend when I can.

**Comment by JamePeng** [comment]
Have a good night! :)

**Comment by J-D-K** [comment]
Working on it now.

**Comment by J-D-K** [comment]
@JamePeng I'm hoping this will do it.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/4712612/JKSV.zip)

**Comment by JamePeng** [comment]
let me try : ) 
Edit: yeah, it was fixed! thank you!
