### ISSUE TITLE
Folder date format naming changed

### ISSUE THREAD

**Issue by ddfault** [J-D-K/JKSV#39]
I am very grateful your application was able to backup saves others could not! Thank you for providing this functionality for system-wide game saves.
I just upgraded from 03.21.2020 to 05.20.2020 and the Icons are now wrapping around instead of showing up in one row. (No big deal) I still and unable to make a new backup of Animal Crossing in Device Saves or BCAT (Also no big deal as I can use Dump all from Device Saves and BCAT to backup my Animal Crossing) My Issue come in that the naming of the folders has changed!
I'm used to seeing:
BCAT - 2020.06.02 @ 18.01.10
and
Device - 2020.06.02 @ 18.01.00
but now they show up as:
BCAT - Wed Jun  3 11_24_28 2020
Device Saves - Wed Jun  3 11_24_16 2020
This doesn't help me keep these folders in chronological order so the new ones are easy to find. How can I got back to the older folder date format?

**Comment by J-D-K** [comment]
Hold down R while selecting new folder for the games you want and it'll follow the same format as before and name it for you. I switched Dump All to use the standard `asctime` C function.

**Comment by ddfault** [comment]
That worked! I was able to hold R and press A while on New and it actually made a backup whereas just pressing A on New does nothing. The text at the bottom of the screen that says LR Auto invoke in me to hold L or R while pressing A for backup. Holding L and pressing A while on New doesn't seem to have the same affect as holding R. So not sure how I was supposed to figure this out. 
Thank you for your quick response! Add a note somewhere or entry in options?

**Comment by J-D-K** [comment]
I changed the string recently to be a bit more clear about that. It just hasn't been released yet. 
![2020060313035600-7EF207E2B57A2E283A114282DE633B17](https://user-images.githubusercontent.com/39171744/83669946-610fd780-a5a0-11ea-8db3-63b42173732d.jpg)

**Comment by ddfault** [comment]
That looks so good! The fact that L+A does YYYY.DD.MM and R+A does YYYY.MM.DD is still not clear but the fact both have to be pressed definitely comes across.
![2020060312560800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/7560310/83671333-24d97880-a59a-11ea-9923-78bf6591ab97.jpg)

**Comment by ddfault** [comment]
This all used to be on one row before.
![2020060312551900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/7560310/83671380-3fabed00-a59a-11ea-83af-4824d88b25a5.jpg)

**Comment by J-D-K** [comment]
That's on purpose. The user select screen is/was a copy paste of the game select screen. It has no reason to support more than 14 or 15 users so I centered and wrapped them.

**Comment by ddfault** [comment]
OK gotcha.
