### ISSUE TITLE
Text Mode button text still shows Text Mode even after switching to Text Mode

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [J-D-K/JKSV#4]

**Comment by J-D-K** [comment]
So, you want it to say Text Mode bigger so you know it's in Text Mode?

**Comment by ThatNerdyPikachu** [comment]
No, can it say "Graphcial Mode" or smth?

**Comment by J-D-K** [comment]
I was kidding. I switched it to say "GUI Mode". Once I'm 100% sure I'm not leaving something unfinished, I'll push it.

**Comment by ThatNerdyPikachu** [comment]
Alright, sorry, heh
