### ISSUE TITLE
Empty save For Xenoblade Chronicles Definitive Edition

### ISSUE THREAD

**Issue by graouu91** [J-D-K/JKSV#41]
Hi, i can restore many backups of my games but for Xenoblade Chronicles Definitive Edition, when i made a backup and restore, the folders are empty with nothing else inside. So sad, i loose so many hours iam going to cry. Same thing with "checkpoint".

Do you have an idea ?

Thanks

**Comment by J-D-K** [comment]
Hi, I'm really sorry to hear that. I've actually been using JKSV to keep a backup of my own Xenoblade save and haven't been having any problems. I even completely erase mine from my system and write back before pushing any major changes to git.
![2020060614295100-F058DE97C24A66F72C26B8C9E916493D](https://user-images.githubusercontent.com/39171744/83951962-76387080-a803-11ea-90b0-678fd92ce7af.jpg)
That is what I get from a backup. I don't know where you are in the game, but I'm willing to give you a copy of mine if it helps at all.

**Comment by graouu91** [comment]
Thanks, I think i made a mistake somewhere, i had just to understand where. It works for you, it's principal, imust made wrong. Thanks.

**Comment by J-D-K** [comment]
Well, it _could_ be a bug you're experiencing that I am not for some reason. I'll attach my save data for you. You can try to extract it to your SD and  restore it to see what happens. If it fails to do that, it might be a problem with JKSV.
[XCDE - Backup.zip](https://github.com/J-D-K/JKSV/files/4740982/XCDE.-.Backup.zip)

**Comment by graouu91** [comment]
Thanks you very much. Iam goint to try this. thanks for all.
