### ISSUE TITLE
JKSV No Longer Able to Launch

### ISSUE THREAD

**Issue by sapphitone** [J-D-K/JKSV#42]
Made an account to post about this issue since I'm not sure of how to fix, but after updating to the latest version of Kosmos, JKSV is no longer able to open, saying the software will close as an error had occurred. Everything worked fine before updating. I've tried the 5-20-2020 release and a GBATemp version from today and nothing seems like it's working.

**Comment by J-D-K** [comment]
I thought kosmos was over with? Run this and check the log file in your JKSV folder. If it doesn't end with `END data::loadUsersTitle();`, it's getting stuck on the last title id. Let me know what it is and add it to the blacklist.txt file. That should get it going for now, at least. It's getting really late for me, or I'd do more for ya.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/4741458/JKSV.zip)

**Comment by J-D-K** [comment]
Gonna close this, but if you still need help, you're more than welcome to reply. I'll see it.
