### ISSUE TITLE
Automatic backup not staying off when turned off

### ISSUE THREAD

**Issue by RednocNivert** [J-D-K/JKSV#43]
This might have to do with specifically Animal Crossing data, but when i change the 'auto backup' to 'OFF' it will be 'ON' again once I come back to the menu to swap saves around again.

**Comment by J-D-K** [comment]
Are you pressing plus to exit? Everything is saved at exit, but using the home button and exiting doesn't break the main loop like I remember on 3ds.

**Comment by RednocNivert** [comment]
That would do it.  Disregard, issue was user error on my part.  Apologies.
