### ISSUE TITLE
Advice to JKSV

### ISSUE THREAD

**Issue by Aeuko** [J-D-K/JKSV#44]
I hope that the JKSV directory will be migrated to Switch/JKSV

I think this is what most people want because it makes it easy to manage our software

**Comment by fennectech** [comment]
Sweet.    :).

**Comment by Aeuko** [comment]
> Put the attached text file in your switch homebrew folder. You can set JKSV to use whatever you want this way.
> 
> @fennectech I can't really do that. The config file is just a bunch of bits to switch bools on and off.
> [jksv_dir.txt](https://github.com/J-D-K/JKSV/files/4761149/jksv_dir.txt)

Thanks for helping me a lot
