### ISSUE TITLE
exefs dumping?

### ISSUE THREAD

**Issue by pixeltester** [J-D-K/JKSV#45]
Hello JK. I love the feature to explore and dump files from romfs, I was wondering if you could expand that to include exefs for dumping game executables with JKSV?

Thank you

**Comment by J-D-K** [comment]
I'll see if it's possible and get back to ya. I'm working on a big project with someone right now, so it might take a little while.

**Comment by J-D-K** [comment]
Worked on this a little today. If this is possible, it's not as simple as the way I get to the romfs. Still gonna work on it when I can.

**Comment by pixeltester** [comment]
Since this issue I've discovered there are other tools dedicated to this (nxdumptool does exefs and romfs for example) so I don't think this is worth keeping open as a request for JKSV these days, thanks.

**Comment by J-D-K** [comment]
OK. Romfs was added so I could grab single files without dumping the whole thing. Sorry I couldn't help more. I don't have a huge amount of time to work on jksv and certain things take priority.
