### ISSUE TITLE
if I make a new folder "D" from macOS , it will be file "F"

### ISSUE THREAD

**Issue by JokerCatz** [J-D-K/JKSV#46]
it worked , but if I make a new folder from macOS , and put files to the folder , JKSV will display "F" in file mode

and if I use the folder to import saves , JKSV will be crash ...

macOS v10.15.5 , exfat , JKSV v06.07.2020 , I had been deleted all dirty data (like `.DS_store` ; `.Trash` ...)

but if I use the folder is make from JKSV , like multiple times to save and put the files to the folder , and use file mode to one by one rollback , will be okay (I think rollback from the folder will be okay too)

anyway , many thanx for this tool , it very useful : )

**Comment by J-D-K** [comment]
Do other apps see them wrong too? I don't know many people with Macs and this is the first I've heard of this.

**Comment by J-D-K** [comment]
Closing this because of no reply. If it's still a problem, feel free to let me know.
