### ISSUE TITLE
titleDefs.txt seems to not be working

### ISSUE THREAD

**Issue by Elionna** [J-D-K/JKSV#47]
I made a txt file and dropped it into the JKSV folder, when I try to backup a save though, the app displays the contents of the entire JKSV folder instead of the properly named folder

[titleDefs.txt](https://github.com/J-D-K/JKSV/files/4829258/titleDefs.txt)

**Comment by J-D-K** [comment]
Does it happen for all you've added, or just one in particular?

**Comment by Elionna** [comment]
Happens for everything I have added

**Comment by J-D-K** [comment]
The quotes you are using are unicode and that is causing the problem. I'll attach a fixed, working version of your file. JKSV only recognizes the standard `"` as a quote to start and stop at.
[titleDefs.txt](https://github.com/J-D-K/JKSV/files/4840522/titleDefs.txt)
