### ISSUE TITLE
Deleted save from Device Saves screen, Want to recover archive 

### ISSUE THREAD

**Issue by Mrliverdog** [J-D-K/JKSV#48]
Hey Just wondering whether it's a possibility. I accidentally deleted my animal crossing save from the backup menu, it says it leaves an archive of that save I'm just trying to recover it. 

Thanks

**Comment by J-D-K** [comment]
If you have a backup, you can restore it and it'll be fine. If not, no, sorry. Archive refers to the files on NAND that hold the filesystems saves use.

**Comment by Mrliverdog** [comment]
I have a backup from like a week ago so I restored that but I was just wondering whether there is a possibility of retrieving that archive. So is this not a possibility?

**Comment by J-D-K** [comment]
No, it's not possible. I don't think you understand what I mean by archive in this case. When you start a game, it creates a filesystem image that stores all the save files in it. That's what I mean by archive. The difference between the two save erasing functions is that one completely removes that image and the second (in the folder menu) wipes the save data, but leaves the image on NAND so the game doesn't recreate it. 

Sorry for the confusion. Once you start adding more powerful options, it starts to get kinda tricky to explain everything without getting really technical and confusing.
