### ISSUE TITLE
Error codes trying to connect to Online Services

### ISSUE THREAD

**Issue by miniblick** [J-D-K/JKSV#49]
After using the save manager, Animal Crossing will not allow me to connect to online services. Every other game works perfectly fine online. I've tried resetting my console and not using the save manager to alter the game and online works fine, it only gives me errors after i actually use JKSV to transfer save data.

**Comment by J-D-K** [comment]
Are you editing the save?

**Comment by miniblick** [comment]
> Are you editing the save?

Yes I was, after reverting the save to an older version on my original island, everything started working fine. I've followed up with the creators of the save editor to let them know. This issue was resolved
