### ISSUE TITLE
automatic Date

### ISSUE THREAD

**Issue by crazyp187** [J-D-K/JKSV#5]
Can you please re add the feature to insert the actual Date/Time by pressing R/ZR, when making a Backup like in the previous build? Would be nice!

**Comment by J-D-K** [comment]
Maybe the inline keyboard is different, but once `swkbdShow` is called, I can't do anything to the string. The applet takes over. That's why I waited until I had the user dictionary figured out to do a new release. Typing in 2 should bring up both date formats.

**Comment by crazyp187** [comment]
Ah i see, thanks for the Info! It works perfekt thank you!
