### ISSUE TITLE
Question about fixing validation of NAND side system title save

### ISSUE THREAD

**Issue by CaiMiao** [J-D-K/JKSV#50]
I wanted to edit my [System Savegames](https://switchbrew.org/wiki/Flash_Filesystem#System_Savegames) directly, but JKSV can't just export my desired save file e.g. `8000000000000050` for `SystemSettings` (occupied and cannot access).

I can edit it manually through direct manipulating on an EmuNAND, but I don't know how to fix the validation (not really understanding every part of it), and results unable to boot.

I have asked on GBATemp but seems no one interested in it. I want to know how can I fix the validation. ofc it would be best if we can have a side function in JKSV to do the fix.

**Comment by J-D-K** [comment]
I don't think this is possible while in Horizon. Terminating the settings process and opening it afterward is what you normally can do, but doing that for system settings will crash the whole Switch. As you said, the save is mounted and I can't touch it currently.

**Comment by CaiMiao** [comment]
how about fixing it on a extracted save? treating a file as a system savegame, and just fix its validation. eventually let user import it himself to nand
