### ISSUE TITLE
(Enhancement) display all games installed on the system as well as displaying games in which save data is present instead of just showing save data which has been generated already..

### ISSUE THREAD

**Issue by Aliasim800** [J-D-K/JKSV#52]
This can be very convienent in some instances when transferring big batches of saves for lots of games because otherwise you would have to go through all the games you want to restore saves on and open and close them to generate a save to restore/overwrite. But as well as displaying the games installed on the system you should also to show saves of games that have been generated because if you for example played witcher 3 and generated a save there and decided to delete it, you would still want it to show up in jksv even if its not on the system anymore, the save is. Hope you understand what i mean.

**Comment by J-D-K** [comment]
I think I do. I recently wrote code that can create the file systems directly in JKSV, meaning you no longer would have to boot up the games first. It's not completely ready yet though. I'm still working some things out.

**Comment by Aliasim800** [comment]
yes, that is what I would like you to implement "meaning you no longer would have to boot up the games first". 
I hope this comes soon and Thanks for reaching out. Keep up the great work!

**Comment by Aliasim800** [comment]
But obviously remember that only games shouldn't show up, saves should too as well as all the games on the system. For example if i deleted witcher 3 and i played hours upon hours i would still want it to show up on jksv even if its not installed on the system. Hope you understand this too.

**Comment by Aliasim800** [comment]
Oh I've seen that you've made another repository related to this issue. Thanks for reaching out!

**Comment by J-D-K** [comment]
Giving an update. Not sure if this is going to happen. I've just noticed that while my code works to create the save file systems, the data I can pull from the system results in them being larger than they normally would be. I'm still searching around, but if I can't nail the size down correctly, I might have to drop it.

**Comment by Aliasim800** [comment]
Hmm hope this goes well, would be disappointing if it gets dropped...
Hopefully you'll figure something out.
Good luck!

**Comment by J-D-K** [comment]
I got it working correctly. It's still going to depend on people willing to run the info dumping app. I really doubt there's any other way to obtain the information needed.

**Comment by Aliasim800** [comment]
Glad you got it working, though what do you mean by saying "It's still going to depend on people willing to run the info dumping app" why would it depend on that?

**Comment by Aliasim800** [comment]
Ah i understand now. It doesn't matter too much if there isn't another way to obtain the information needed, running something to obtain it is still good enough in my opinion.

**Comment by JBx0** [comment]
> I got it working correctly. It's still going to depend on people willing to run the info dumping app. I really doubt there's any other way to obtain the information needed.

got a commit one can check out?

**Comment by J-D-K** [comment]
Sort of done. newUI branch allows you to create saves without needing to start anything. They're not displayed, but the user options menu allows you to select and create what you want for any user on your system. Bcat, cache, and device saves included.
