### ISSUE TITLE
(Issue, needs to be fixed) having trouble restoring completely fine Pokemon quest Save.

### ISSUE THREAD

**Issue by Aliasim800** [J-D-K/JKSV#53]
So i was busy doing some stuff on my switch like backing up restoring saves then i found out that my pokemon quest save wasn't being restored, no matter what it just didn't want to restore. I took the same save and restored it with checkpoint and it worked fine. So it seems to be an error with jksv. Hope this can get fixed.

Here is an image of the error:
![ivK5](https://user-images.githubusercontent.com/64366457/88477613-86361c00-cf39-11ea-8429-7fbaa0c38945.jpg)

**Comment by J-D-K** [comment]
OK. Noted.

**Comment by J-D-K** [comment]
I removed this space check because it never seemed to work right even though it should have.
