### ISSUE TITLE
Restoring Ring Fit Adventure Save results in error

### ISSUE THREAD

**Issue by sevenpoundowl** [J-D-K/JKSV#58]
I'm trying to restore a Ring Fit Adventure save but every time I do I get the following error:

However, when I restore anything else it seems to work fine. Any idea on how to fix this?

**Comment by J-D-K** [comment]
I removed that free space check because it kept doing that. Not sure why. Here. This should get around that. Let me know how it goes.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/5249549/JKSV.zip)

**Comment by sevenpoundowl** [comment]
That worked. Thank you so much! Ring Fit Adventure crisis averted...my wife thought she had lost 5 months of progress.

**Comment by apassiou** [comment]
Ran into same issue. When will a build be released with the fix?
