### ISSUE TITLE
JKSV ‘no save files’ and no user name

### ISSUE THREAD

**Issue by leinaa** [J-D-K/JKSV#59]
![AFE3E5CB-2CEC-498F-ADEF-B70AE56B05A9](https://user-images.githubusercontent.com/71921729/94336064-06f2b200-ff95-11ea-8ca5-d3cecae8f63a.jpeg)
Hi Im running into the problems as i try to open jksv for animal crossing but it didnt has any username for me to choose- only device and when I click on device it said ‘no save files’ I saved my game and didnt closed it completely- what am i doing wrong? TIA

**Comment by J-D-K** [comment]
If you didn't close the game, the save is still mounted by Animal Crossing. JKSV won't show games it can't mount by default.
