### ISSUE TITLE
Can not restore a save from Unravel Two

### ISSUE THREAD

**Issue by fabsau** [J-D-K/JKSV#60]
Hello there!
Unfortunately I can not restore my save for the game Unravel Two.
I get the following error message:
"Error committing file to device"

The backup has the following structure
SAVEDATA01/profile.pro

The same error message pops up if I try to copy the save via file mode (with "Write to Sys Saves" enabled). I am also not able to create files/folders on the left panel (sv:)

I am open to help you to troubleshoot this issue, let me know if you need anything from me :-)

JKSV: v.06.07.2002
FW: 10.1.0
Atmosphere: 0.14.4 on EMUMCC
Payload: Argonnx

Thank you very much in advance and kind regards

**Comment by J-D-K** [comment]
This sounds like a journal space error which should be fixed in the latest release and newUI branch. But, if it's not let me know.
