### ISSUE TITLE
Feature request. “Ignore spesific directories for save backup and restore

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#62]
I would love to be able to prevent backup of spesific folders in the save archive on a per game basis.  This would be incredibly useful on games like minecraft with thousands of files totaling to gigabytes in size all in the "premium cache" directory of the save container.  If we could ignore this folder when creating backups and restoring them. This would allow for significantly smaller backups with no loss in usability for the game. (Basicly ignore the premium cache when backing up and restoring).  It would be perfectly acceptable if this required prepairing json files with the paths manually.  Just chucking them in the games directory would be a perfect solution

**Comment by J-D-K** [comment]
OK. I'll see what I can do. Sounds simple enough.

**Comment by fennectech** [comment]
EPIC. Can those directories be ignored when restoring a save too?  So they aren't deleted from the save archive?

**Comment by J-D-K** [comment]
That's part of what needs to be figured out. I wrote all the code for that stuff myself, so I have an idea of how to implement it. Just don't have time right this moment to do it.

**Comment by J-D-K** [comment]
@fennectech 
If you don't mind testing it, here is a build that _should_ support this. Keep a good backup somewhere just in case. I've given it a few tries and it seems to work. Put a text file named `pathFilters.txt` in the folder of the game and add paths to files or folders, e.g. `sv:/path/to/folder`. **Don't** put a trailing slash for now. This list should prevent them from being copied from the save data and prevent them from being wiped on restore. Let me know how it goes.
[JKSV_12.04.2020.zip](https://github.com/J-D-K/JKSV/files/5646440/JKSV_12.04.2020.zip)

**Comment by fennectech** [comment]
Sweet r  looks to work so far!  ive tried bolth back up and restore
