### ISSUE TITLE
[Question] Restore to another user of switch ?

### ISSUE THREAD

**Issue by LiloBzH** [J-D-K/JKSV#63]
Hi !

Question is in title.

Is it possible or there is no solution to restore a backup to another account ?

Thank you

**Comment by fennectech** [comment]
I'm unsure how users work. But it most definitly should be possible.   Just a mater of putting the files in the right place.

**Comment by fennectech** [comment]
Safe to be closed    @LiloBzH  It currently does that   Saves arent sorted by user  you can just restore the save from the other users point of view (selecting them in the jksv user selection screen)

**Comment by LiloBzH** [comment]
for me it doasn t work.

You have tested ?

**Comment by fennectech** [comment]
I made another user and the saves show up. What happens when you do it?

**Comment by LiloBzH** [comment]
my mab. i tested only with Unravel Two and there is a bug !

it's ok now

**Comment by J-D-K** [comment]
I guess this is OK now? Closing. Confused also.
