### ISSUE TITLE
JKSV crash (backup/restore "My Diggy Dog 2" game)

### ISSUE THREAD

**Issue by MAN-biker** [J-D-K/JKSV#66]
JKSV crashing while trying to restore "My Diggy Dog 2" game or backup it (if use "file mode", the reason is **data2с** save file).
So, as I understood, JKSV can't handle **data2с** file of "My Diggy Dog 2" game saves.

Firmware : 10.1.0
CFW : Atmosphere 0.14.1
JKSV version : 06.07.2020
FAT32 (checked, no errors in FS)

**Comment by J-D-K** [comment]
Sounds like journal space issue since it's only on restore. I don't have the game to check myself, but feel free to let me know if it's still an issue for you with newer releases.
