### ISSUE TITLE
[Feature request]  Automaticly highlight overridden title.

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#67]
Would be neat if the title that is being overridden would be the one that is highlighted on launch  would be useful for things like savescumming or save modding.    As the title your currently playing with is usually the title you want to backup or restore

**Comment by J-D-K** [comment]
This is doable. Not sure when I'll be getting to these though.

**Comment by J-D-K** [comment]
Is this really needed now? Setting sort to last played kind of accomplishes this.

**Comment by fennectech** [comment]
Not Really :)
