### ISSUE TITLE
BCAT mounting

### ISSUE THREAD

**Issue by iUltimateLP** [J-D-K/JKSV#69]
Hey! Great work on JKSV, using this for months now for my ACNH saves. I'm also a developer who has fiddled around with Homebrew apps, and I've had the idea to create an app (or sysmodule) which automatically downloads and mounts the latest BCATs for the events or ACNH. It would be easy to provide a server which contains the BCATs and download it, however the mounting part needs to be safe. 

My question: do you have anything against the fact that I'm looking at the source of JKSV and toying around with the BCAT code? Thanks!

**Comment by J-D-K** [comment]
`fsOpen_BcatSaveData` is what you need to use. Libnx provides this function now, so you don't need anything custom like I used to use. 

I don't mind at all. If you need any help finding something, let me know. I'm far from a pro and don't plan things out well. Things can be a mess.

**Comment by DanMossa** [comment]
@iUltimateLP That would be awesome! I would be a user of that

**Comment by iUltimateLP** [comment]
![Album_5_12_2020_13_26_15](https://user-images.githubusercontent.com/8491339/101242989-68ee3700-36fd-11eb-88e7-b89deeaf1c01.jpg)
First success :)
