### ISSUE TITLE
No control for "blacklisted" games (?)

### ISSUE THREAD

**Issue by r4dius** [J-D-K/JKSV#7]
Hi, I'm not sure if I'm right but there seems to be no way to un-blacklist a blacklisted game (?),
I may try to look and add some way but I'm not that great at real coding c ^^

**Comment by J-D-K** [comment]
I'll get to it sometime soon. I've been meaning to do it for a while, actually.

**Comment by r4dius** [comment]
Thanks :)
Btw I''ve been tweaking some things to match the switch menus, stills needs a lot of work but if you'd have a look I add some screenshots to the project

**Comment by J-D-K** [comment]
Sorry, I didn't forget or anything. I'm just having a difficult time figuring out how to implement it. It's gonna require rewrite part of how JKSV boots and loads.

**Comment by r4dius** [comment]
I've been working on a redesign fork for some time if you wanna give it a try, I added a simple blacklist handling (won't list games in the list that aren't in the system) : https://github.com/r4dius/JKSV

**Comment by J-D-K** [comment]
It's been 3000 years, but finally done. I actually took a look at your fork back then and thought it was cool how you made it match the Switch's UI closer. Don't know if you care anymore, but it's done. The slide out panels free up and make adding things easier.

**Comment by r4dius** [comment]
Thanks, I'll have a look at this :)
