### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#71]
Could you make the Auto option bound to a single button? Instead of a button combo?  Its way easier to use than manually typing a name

**Comment by fennectech** [comment]
Ether that or when the keyboard is dismissed with start and is empty use the current date and time

**Comment by J-D-K** [comment]
I'm going to add it as a setting you can toggle. If it's on, it just auto names it for you.

**Comment by J-D-K** [comment]
Done
