### ISSUE TITLE
hi, the JKSV is not working for me.

### ISSUE THREAD

**Issue by omegar1999** [J-D-K/JKSV#72]
When I enter I do not get users next to decives, which I do not know if it will be normal or not.
but when trying to back up or restore my acnh save file, nothing just happens. When I got back into the game, nothing has changed at all, and I would like to know if the reason is a bug or something.
my version of atmosphere is 0.16.1. thanks

**Comment by J-D-K** [comment]
If there aren't any saves for any users, it is normal to only have system saves. Are launching with the album?
