### ISSUE TITLE
Can't find my saves

### ISSUE THREAD

**Issue by alxbrrn** [J-D-K/JKSV#73]
Hi, I made a backup of all my saves because I had to restore my Switch. I copied them to my pc, restore the Switch and hack it again but, whe I copy my saves to the sd card to restore them, JKSV doesn't seem to find them, what can i do?

**Comment by J-D-K** [comment]
Which way did you do it? Pressing Y? Or, the extra option to zip everything? If you used the zip one, you need to unzip the file and put it on your SD.

**Comment by alxbrrn** [comment]
i did it pressing Y. Could It be because of emummc?

**Comment by J-D-K** [comment]
No, JKSV only uses the SD card. You just copied the JKSV folder to your SD root, right? That's the default place to look.

**Comment by alxbrrn** [comment]
Yeah, I copied it there. What could it be?

**Comment by J-D-K** [comment]
Sorry. I was busy. I'll get back to ya later to try to see what's up.

**Comment by alxbrrn** [comment]
i solved It! i didnt know the saves were inside the game
