### ISSUE TITLE
Error 2168-0002 after updating Atmosphere and OS to latest release [FIXED]

### ISSUE THREAD

**Issue by walppeople** [J-D-K/JKSV#74]
I've been using JKSV for a long time without problems. My latest setup was Atmosphere 0.12 and OS 10.0.2. Yesterday, I updated both Atmosphere and OS to their latest release. Since then, I'm consistently getting error 2168-0002, program ID 010000000000100D whenever I launch JKSV through hbmenu in Applet Mode. if I launch it pressing R to accces hbmenu first, I get a standard error black screen (The software was closed because an error ocurred). All other software or homebrew apps work fine as always. I'd appreciate suggestions if I did something wrong or a quick fix if the problem is related to JKSV, it really is the best save manager around! Thanks and happy holidays!

EDIT: Solved. If anyone encounters this same issue, try deleting all custom titles in folder atmosphere>titles, they might be causing some issues with other software/homebrew.

**Comment by impeeza** [comment]
are you running as an title replacement or in applet mode?

this is a space for issue and bug report, for support please go to Discord or GBATemp
