### ISSUE TITLE
Issues saving / restoring ACNH saves after upgrade to HOS 11.0.1 - 0x4A8 (2168-0002)

### ISSUE THREAD

**Issue by svarold** [J-D-K/JKSV#75]
Hi,
I've been using JKSV for a number of months with Atmosphere by using the guide to install cfw in https://nh-server.github.io/switch-guide/

Since upgrading to HOS 11.0.1, I have not been able to save or restore ACNH saves.

I am doing this offline in SysMMC mode.  I tried in emuMMC mode, and had inconsistent results.

I built a fresh CFW environment using both the above nh-server guide, as well as a couple of others with the minimum available tools.

I am using:
Hekate - CTCaer mod v5.51 & Nyx v0.9.7
Atmosphere 0.16.2
HOS 11.01
JKSV 06.07.2020

I have tried downgrading JKSV to 05.20.2020.
I have tried downgrading nx-hbloader to v2.3.2
I also tried Atmosphere 0.16.1 (earliest support of HOS 11.0.1)

I tried in applet and in application mode (R + A when loading an existing program).

Saving and loading user games like Dragon Builders works fine, but when trying to perform actions on ACNH, it crashes, if it is a restore, it destroys the system save.

Edit - Also I can confirm the SDCard is FAT32, not exFAT.

[crash report.txt](https://github.com/J-D-K/JKSV/files/5749785/crash.report.txt)

Attached a crash report.

I have had a look through the closed issues and on a few places on the internet, but none seem to work or figure into my setup - I dont have a titles folder in atmosphere, so I don't think that's the issue as per #74 

I'm stumped.  Do you have any suggestions or can you help?

cheers,
Jon.

**Comment by J-D-K** [comment]
It probably won't make a difference, but... On the user select screen, can you press minus and turn on Direct FS Commands and let me know if the same error occurs? If not, I'll check in later to try to get to the bottom of it.

**Comment by svarold** [comment]
Hello,

So I did a format (fat32) and rebuilt the sd card from scratch again, using:
https://www.sdsetup.com/console?switch#atmosphere;atmos_musthave;hekate_musthave;tesla_menu;atmos_ovlloader;atmos_sys-clk;atmos_sysftpd;ovl_sysmodules;appstorenx;hbmenu;edizon;jksv;goldleaf;nxdumptool;lockpick;hekate;lockpick_rcm;tegrarcmgui;

I've done it a couple of times that way.
I then copied the saves across to the newly built SDcard.
On the user select screen, I enabled Direct FS Commands.

It worked.  I was able to successfully backup the save from SysNand to the SD card.  I then restored a different save.  It worked fine.
I restarted the switch and verified that the save was OK.  I was able to load ACNH with the expected save with no issues!

I jumped back into the CFW, and attempted the same without the Direct FS Commands enabled - crashed.
I then went back and restored everything and tried again with Direct FS Commands enabled, worked fine.

I think I tried this earlier, but obviously there was something else in the mix messing with it.

btw - I mistakenly tried restoring "New" and it crashed with the same message.

**Comment by J-D-K** [comment]
Ok. Direct FS Commands runs through a custom sort of wrapper I wrote, the other uses libnx's default stdio. I'll check it out, but I don't have animal crossing to test.

**Comment by svarold** [comment]
Much appreciated.  I don't get paid until the 15th of Jan, so if you have an amazon wish list link for it, I can give you a copy after then.

**Comment by J-D-K** [comment]
Sorry, I disappeared. Anyway, I appreciate the offer, but I don't feel comfortable accepting donations. Thanks though. I'm not sure what I can actually do about libnx's stdio, but as long as direct fs covers this, I don't think it's a problem.
