### ISSUE TITLE
Title selection view is in wrong state after save erasing

### ISSUE THREAD

**Issue by cdriper** [J-D-K/JKSV#77]
Preconditions:
- you need more than 32 titles installed 

Steps to reproduce:
- scroll down title view so a first title on the screen has at least index 8
- press ZR and erase save data for a title 

App enters a wrong state: 
- cursor is rendered in previous position on the screen 
- title with index 0 is selected actually 

Bug cause:
Only data::selData is cleared after save data deletion so start variable stays with a wrong value.  
I think you need to call reset() (instead of selData = 0) to fix this bug.

**Comment by J-D-K** [comment]
I'll check it out when I can. I'm rewriting a good chunk of the data file so I'll need to fix it after that.

**Comment by J-D-K** [comment]
Gonna close this one. newUI branch's titleview class checks this when update() is called.
