### ISSUE TITLE
Error committing to device with Unravel Two

### ISSUE THREAD

**Issue by escape75** [J-D-K/JKSV#78]
I made a save in JKSV then removed save game data and tried restoring from SD Card using JKSV
and could not with above error ...

Furthermore after the restore attempt the AutoBackup as well as original Save Backup gets removed - become empty folders,
and the save on the Switch itself gets reset as well, basically forcing user to start the game from beginning.

Looks like the other issues are somewhat related:
https://github.com/J-D-K/JKSV/issues/79
https://github.com/J-D-K/JKSV/issues/60

**Comment by JBx0** [comment]
+1

**Comment by J-D-K** [comment]
Does this still happen with the latest release? Most of the commit errors seem to be because of journal space running out. Latest release with the snap fix should bypass this.
