### ISSUE TITLE
Error copying save data with Max: The Curse of Brotherhood

### ISSUE THREAD

**Issue by escape75** [J-D-K/JKSV#79]
I made a save backup with JKSV, then removed the save data on switch, stated the game and then tried restoring.
I got an error message telling me than there was an error copying save data ...

**Comment by J-D-K** [comment]
Can you try pressing minus on the user select screen and turning on the `Use Direct FS Commands` option and see if that makes a difference?

**Comment by escape75** [comment]
This is interesting, I tried again to make a new backup and restore and it was failing ...
Then I tried "Use Direct FS Commands" and made a backup and restored and it worked ...

However after further examination the folder with the backed up save is empty, so it never backed up anything!

**Comment by whitezombie2000** [comment]
I have the exact same issue when trying to restore a save from The Messenger. I get Not enough free space to copy error and the save is not restored. Furthermore, the existing save on the nand gets wiped, and using Direct FS Commands doesn't help.  I am using Atmosphere 0.19.1 and EmuNand. I tried the latest snapshot of EdiZon and had no issues dumping and restoring with The Messenger.

**Comment by J-D-K** [comment]
I removed the free space check, so it shouldn't be an issue anymore. I'll close this now, but if it's still a problem, let me know.
