### ISSUE TITLE
Some created save directories use TitleID instead of title name

### ISSUE THREAD

**Issue by murrty1** [J-D-K/JKSV#8]
For some games (so far, Pokemon Let's Go Pikachu/Eevee, Pokken Tournament DX), the save directory is titled with the 16-char TitleID.

010003F003A34000 should say Let's Go Pikachu
0100187003A36000 should say Let's Go Eevee
0100B3F000BE2000 should say Pokken Tournament DX

**Comment by murrty** [comment]
This isn't related to the issue, but I also wanted to say this is my favorite save export/import homebrew, as well as your 3DS one.

**Comment by J-D-K** [comment]
Switch can't use UTF16 like 3DS. This is normal. It's the accented e that causes it. I think I added code for someone that replaces it, but I haven't had time to complete that yet.

**Comment by AnalogMan151** [comment]
Even if it could replace invalid chars with an underscore or space, it would still make it easier finding the save on the SD card.

**Comment by J-D-K** [comment]
Sorry it took so long, but I don't think that's doable. It would replace all Japanese characters with underscores and spaces, which could lead to a lot of issues.
