### ISSUE TITLE
Zip save issue - Software was Closed

### ISSUE THREAD

**Issue by dhattey** [J-D-K/JKSV#80]
I'm fairly new to JKSV and really appreciate it!  I've bumped into a problem, may be simple but I'm at a loss.  I saved one session to zip and it worked fine.  The next time I used it the software closed about two thirds of the way through the save - in other words it started saving, was into postal area, and closed.

I've tried reloading, even tried a whole new SD card which I built from scratch - have not had a successful zip save yet.  Also tried both direct FS command setting as well as STDIO setting - same results.

Any avenues of investigation or ideas for resolution would be appreciated!
thanks
Dave

**Comment by J-D-K** [comment]
It appears that the direct FS command option doesn't affect the zip functions at the moment. You did format to fat32, right? I know it gets old, but it is important.

**Comment by dhattey** [comment]
Yes, Fat32

**Comment by J-D-K** [comment]
Sorry I disappeared. I didn't mean to leave ya hanging. An error should pop up if it's having issues opening or writing a file into a zip. If it's just hanging, there's something somewhere I have to find.

**Comment by J-D-K** [comment]
Gonna close this cause of no reply. If it's still an issue, reply and let me know.
