### ISSUE TITLE
Files / folders ending in a period confuse windows.

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#83]
This causes annoyance when using a windows computer to manage these files

**Comment by fennectech** [comment]
![274136F8-3FA5-4C89-A68A-AA1635D4BA9E](https://user-images.githubusercontent.com/11953665/107178783-8c05c300-699a-11eb-8e40-bd5fb7ff761b.jpeg)
![F3861AC9-00BE-44E0-A432-39F81C5F2AAF](https://user-images.githubusercontent.com/11953665/107178786-8f00b380-699a-11eb-8a8a-3fc937ecb8a3.jpeg)

**Comment by J-D-K** [comment]
Ok. I'll add periods to the space stripping thing.

Protip: Print screen and Ms. Paint.

**Comment by fennectech** [comment]
I think its funny that you completely ignored the windows 98 screencaps

**Comment by J-D-K** [comment]
Honestly, I probably just figured it was the base, no frills windows theme. I don't really use Windows for much anymore.

**Comment by fennectech** [comment]
Nah.  The base windows theme hasent been a thing since XP   (At least not in the form)   And it still used the modern icons even then.   That particular system is windows XP with the 2k transformation pack which brings back the look and feel of win2k (the last version with an authentic 90s feel)
