### ISSUE TITLE
Issue with settings on JKSV

### ISSUE THREAD

**Issue by NinFanBoyFTW** [J-D-K/JKSV#90]
Hi, ever since you guys added the settings page to JKSV last year I have been having a couple of issues with it. I personally do not use the auto backup feature or a few other features so I have tried turning them off in the settings. The problem is that after I quit JKSV and relaunch it, all of the settings I changed have been wiped out and it goes back to the default. Am I missing something, or is there a way for you to add some sort of an ini settings file to your sd card so that you can save your settings for JKSV. Thanks again

**Comment by J-D-K** [comment]
>guys
I'm the only dev for JKSV. 

Make sure you're pressing plus to exit. Everything is saved when the main loop is broken. Exiting with the home button doesn't let it save anything.
