### ISSUE TITLE
[Localization updated] Traditional Chinese langs for NEW_JKSV_SNAP_05.04.2021(#89)

### ISSUE THREAD

**Issue by qazrfv1234** [J-D-K/JKSV#92]
Hello,
The new_JKSV_SNAP.nro is working!  
And the attachment is for NEW_JKSV_SNAP_05.04.2021 version (the latest en-US.txt )

[zh-TW.zip](https://github.com/J-D-K/JKSV/files/6442472/zh-TW.zip)

Many thanks,
Leo

**Comment by J-D-K** [comment]
Thank you. I'll check it out and add it when I can. Some time this week.

**Comment by J-D-K** [comment]
Sorry. Been busy. I'll get to it soon.
