### ISSUE TITLE
Compatibilité entre console

### ISSUE THREAD

**Issue by rototo38** [J-D-K/JKSV#94]
Salut à tous, j’ai la dernière version de jksv sur mes deux consoles nintendo switch cependant lors d’un backup avec la première console celui s’effectue sans problème. Par contre sur la seconde console, lorsque je souhaite charger la sauvegarde de la première console la barre de progression charge mais reste bloquée à la fin et le jeu ne prend en compte aucune sauvegarde. Avez vous une idée ? Cordialement

**Comment by fennectech** [comment]
Helpfully Translated it.

Hi everyone, I have the latest version of jksv on my two nintendo switch consoles however when backing up with the first console it goes smoothly. On the other hand, on the second console, when I want to load the save from the first console, the progress bar loads but remains blocked(Stuck?) at the end and the game does not take any save into account. Do you have an idea ? Regards

**Comment by J-D-K** [comment]
Game?

**Comment by rototo38** [comment]
This is Zelda Breath of the wild. I would say that both consoles are equipped with the same software version as well as sx os 3.1.0. From the moment when a backup does not come from the same console it is not useable on the new one

Envoyé de mon iPhone

Le 17 mai 2021 à 06:09, JK ***@***.***> a écrit :

﻿

Game?

**Comment by J-D-K** [comment]
Have you tried with the latest version I uploaded? It sounds like it's having trouble committing the file if it's getting stuck at the end. Newest version would fail sooner or bypass the problem.

**Comment by rototo38** [comment]
It seems to me to have the latest version. I tried with other games but no backup is compatible on the second console if the backup comes from the base of the first console

Envoyé de mon iPhone

Le 19 mai 2021 à 02:46, JK ***@***.***> a écrit :

﻿

Have you tried with the latest version I uploaded? It sounds like it's having trouble committing the file if it's getting stuck at the end. Newest version would fail sooner or bypass the problem.

**Comment by J-D-K** [comment]
I'll get back to you soon. I have to add some logging to get to the bottom of it. Usually that freeze is a commit error, but it should pop up with an error.

**Comment by rototo38** [comment]
Perfect, thank you again for your responsiveness to this problem and to make a correction to it

Envoyé de mon iPhone

Le 22 mai 2021 à 03:02, JK ***@***.***> a écrit :

﻿

I'll get back to you soon. I have to add some logging to get to the bottom of it. Usually that freeze is a commit error, but it should pop up with an error.

**Comment by rototo38** [comment]
Hello, I just reinstall your software in .nsp format on my two consoles. So I made a backup of my Zelda game. I retrieve this backup from the micro sd card on my computer and then copy it to my son's micro sd card. I launch your software on my son's console, I choose my backup and then I restores it but I'm stuck on it at the end

[cid:B30390C0-8DA5-4DDF-801C-C816D427EA1D-L0-001]

Envoyé de mon iPhone

Le 22 mai 2021 à 03:02, JK ***@***.***> a écrit :

﻿

I'll get back to you soon. I have to add some logging to get to the bottom of it. Usually that freeze is a commit error, but it should pop up with an error.

**Comment by J-D-K** [comment]
Can you try the prerelease NRO? I only build the NSP for major releases. The Pokemon Snap fix might fix more than just snap.

**Comment by rototo38** [comment]
I tried with both software formats and it always ends in the same way, as in the photo

Envoyé de mon iPhone

Le 23 mai 2021 à 17:01, JK ***@***.***> a écrit :

﻿

Can you try the prerelease NRO? I only build the NSP for major releases. The Pokemon Snap fix might fix more than just snap.

**Comment by J-D-K** [comment]
Ok. I've been busy the last couple days. I'll upload a logged build tomorrow to see if I can get to the bottom of it.

**Comment by J-D-K** [comment]
Run this and try to restore the save that causes the problem. After that, go into the JKSV folder and get the file named log.txt. Copy and paste it to pastebin and give a link. It should give me a rough idea of what's happening or where it's getting stuck.

[JKSV.zip](https://github.com/J-D-K/JKSV/files/6548835/JKSV.zip)

**Comment by rototo38** [comment]
Hello, my log.txt file is always empty inside and it's zero bytes

Envoyé de mon iPhone

Le 26 mai 2021 à 20:16, JK ***@***.***> a écrit :

﻿

Run this and try to restore the save that causes the problem. After that, go into the JKSV folder and get the file named log.txt. Copy and paste it to pastebin and give a link. It should give me a rough idea of what's happening or where it's getting stuck.

JKSV.zip<https://github.com/J-D-K/JKSV/files/6548835/JKSV.zip>

**Comment by rototo38** [comment]
I have installed your file as an attachment and now the backup goes to the end without any bug. But when restoring the progress bar goes well until the end but then the console does not take into account. I can transfer backups of several games between different accounts but only if the backups come from the same console, if the backup comes from the second console then nothing happens

Envoyé de mon iPhone

Le 26 mai 2021 à 20:16, JK ***@***.***> a écrit :

﻿

Run this and try to restore the save that causes the problem. After that, go into the JKSV folder and get the file named log.txt. Copy and paste it to pastebin and give a link. It should give me a rough idea of what's happening or where it's getting stuck.

JKSV.zip<https://github.com/J-D-K/JKSV/files/6548835/JKSV.zip>

**Comment by J-D-K** [comment]
Are you using zip? If so, that's probably why the log is blank. A different system shouldn't make a difference. How are you moving them to the other system? Have you tried turning on the direct FS command option? I don't have SX and no longer have any testers that use it either.
