### ISSUE TITLE
PathFilters not used when dumping all games

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#95]
PathFilters not used when dumping all saves with "Y" on the home screen

**Comment by J-D-K** [comment]
Oh shit. Thanks. Yeah, it only gets loaded when you open the folder menu.

**Comment by J-D-K** [comment]
Ok, so this and https://github.com/J-D-K/JKSV/issues/83 should be fixed now if you don't mind confirming for me.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/6557036/JKSV.zip)

**Comment by fennectech** [comment]
Works

**Comment by J-D-K** [comment]
Thank you.
