### ISSUE TITLE
ACNH Doesn't Back Up

### ISSUE THREAD

**Issue by sortiara** [J-D-K/JKSV#96]
I updated to Atmosphere 0.19.3, updated hekate, and installed the new JKSV.nro but every time I attempt to back up a save for ACNH, the backup folder remains empty on the SD. I tested it with another game, Monster Hunter Rise, and it backed up just fine. Is there something I'm doing incorrectly?

Edit: And yes, I did go through Device Save.

**Comment by J-D-K** [comment]
You start the game and it's fine though? Doesn't make you start over? If it can't open the save, it shouldn't even show up or let you pick it. Is there anything on the left side if you hit minus on the backup screen?
