### ISSUE TITLE
Preserve timestamps

### ISSUE THREAD

**Issue by benwa** [J-D-K/JKSV#99]
Would it be possible to preserve the original timestamps of both files and folders?

As an example:

- BOTW has saves in folders marked 0-5
- The folders' date are set to 1969-12-31 18:00:00
- The files' date are set to the timestamp the backup is made
- By preserving the timestamps the system/game sets on the saves, it can be easy to tell at a glance which save file the user is interested in.

**Comment by J-D-K** [comment]
There's a function to retrieve the timestamp in libnx but I'm not sure there is one to update it. There's one function I'm looking at, but not sure it'll do what you want. I'll let you know.

**Comment by zand** [comment]
It would be a bit of a hack but one function that likely does effect timestamps is `timeSetCurrentTime`.

**Comment by J-D-K** [comment]
I think that sets the actual system time, looking at libnx's header. I don't think that's going to fix this. What he's talking about is that all folders produced have a modified date of 12/31/1969(USA Here). The files inside are properly timestamped for me too.

**Comment by zand** [comment]
Well what I was getting at is that in the absence of a function to set timestamps, changing the system time temporarily may result in the desired effect. That is assuming that the timestamps are based on the system clock. Its not right way to go about doing it but figure I point out the idea as the wrong way can be better than no way of doing it.

I am still a bit naive on how saves are stored on the switch's NAND so I don't yet know how the timestamps are even recorded let alone a more proper way of setting them. (https://switchbrew.org/wiki/Savegames)

**Comment by J-D-K** [comment]
I don't think he's worried about preserving the timestamps of the save data itself from the file containers on NAND (if it even has them). The issue as far as I can tell is that all folders created on the SD card have a last modified date of 1969, which if you're sorting by date on PC to decide what to keep is a pain.

That's what I observed through ftpd though. Every folder has that date, including the system ones. I'm going to investigate tomorrow since I finally got showMessage added back. It might be an FTP thing. If I can pull modified dates from the folders, then it's probably that.

**Comment by zand** [comment]
I guess that makes more sense. I been connecting to the switch via USB as a storage device and all the folders/files have correct date timestamps. I downloaded ftpd v3.1.0 and connected via that and observed folders having zero for the timestamp while files have the correct timestamp. I assume that this is an issue with ftpd.

**Comment by J-D-K** [comment]
Yep. @benwa you can try starting an issue on the ftpd github to see if it gets you anywhere. If not, maybe I'll take a look at it myself and see if I can fix it and get it pulled. It should be possible if they're displayed correctly over USB.
